import type { DocumentationGroup, DocumentationPageMetadata } from '../models/documentation-page';

const DOCUMENTATION_PAGE_METADATA: readonly DocumentationPageMetadata[] = [
  { id: 'overview', path: 'overview', label: 'Overview', icon: 'pi-th-large', group: 'START HERE', kind: 'overview', status: 'CANDIDATE', searchText: 'Overview overview START HERE overview' },
  { id: 'principles', path: 'principles', label: 'Principles', icon: 'pi-compass', group: 'START HERE', kind: 'principles', status: 'CANDIDATE', searchText: 'Principles principles START HERE principles' },
  { id: 'maturity', path: 'maturity', label: 'Maturity / Freeze', icon: 'pi-bookmark', group: 'START HERE', kind: 'overview', status: 'FROZEN', searchText: 'Maturity / Freeze maturity START HERE overview' },
  { id: 'color', path: 'foundations/color', label: 'Color', icon: 'pi-palette', group: 'FOUNDATIONS', kind: 'foundation', status: 'CANDIDATE', searchText: 'Color color FOUNDATIONS foundation' },
  { id: 'brand-logo', path: 'foundations/brand-logo', label: 'Brand / Logo', icon: 'pi-image', group: 'FOUNDATIONS', kind: 'foundation', status: 'CANDIDATE', searchText: 'Brand / Logo brand-logo FOUNDATIONS foundation' },
  { id: 'typography', path: 'foundations/typography', label: 'Typography', icon: 'pi-align-left', group: 'FOUNDATIONS', kind: 'foundation', status: 'CANDIDATE', searchText: 'Typography typography FOUNDATIONS foundation' },
  { id: 'layout-spacing', path: 'foundations/layout-spacing', label: 'Layout & Spacing', icon: 'pi-arrows-alt', group: 'FOUNDATIONS', kind: 'foundation', status: 'CANDIDATE', searchText: 'Layout & Spacing layout-spacing FOUNDATIONS foundation' },
  { id: 'shape-radius', path: 'foundations/shape-radius', label: 'Shape & Radius', icon: 'pi-stop-circle', group: 'FOUNDATIONS', kind: 'foundation', status: 'CANDIDATE', searchText: 'Shape & Radius shape-radius FOUNDATIONS foundation' },
  { id: 'surfaces', path: 'foundations/surfaces', label: 'Surfaces', icon: 'pi-stop', group: 'FOUNDATIONS', kind: 'foundation', status: 'CANDIDATE', searchText: 'Surfaces surfaces FOUNDATIONS foundation' },
  { id: 'iconography', path: 'foundations/iconography', label: 'Iconography', icon: 'pi-compass', group: 'FOUNDATIONS', kind: 'foundation', status: 'CANDIDATE', searchText: 'Iconography iconography FOUNDATIONS foundation' },
  { id: 'motion', path: 'foundations/motion', label: 'Motion', icon: 'pi-bolt', group: 'FOUNDATIONS', kind: 'foundation', status: 'CANDIDATE', searchText: 'Motion motion FOUNDATIONS foundation' },
  { id: 'buttons', path: 'components/buttons', label: 'Buttons', icon: 'pi-external-link', group: 'COMPONENTS', kind: 'component', status: 'CANDIDATE', searchText: 'Buttons buttons COMPONENTS component' },
  { id: 'text-fields', path: 'components/text-fields', label: 'Text Fields', icon: 'pi-pencil', group: 'COMPONENTS', kind: 'component', status: 'FROZEN', searchText: 'Text Fields text-fields COMPONENTS component' },
  { id: 'search-fields', path: 'components/search-fields', label: 'Search Fields', icon: 'pi-search', group: 'COMPONENTS', kind: 'component', status: 'CANDIDATE', searchText: 'Search Fields search-fields COMPONENTS component' },
  { id: 'select-combobox', path: 'components/select-combobox', label: 'Select & Combobox', icon: 'pi-chevron-down', group: 'COMPONENTS', kind: 'component', status: 'CANDIDATE', searchText: 'Select & Combobox select-combobox COMPONENTS component' },
  { id: 'checkbox', path: 'components/checkbox', label: 'Checkbox', icon: 'pi-check-square', group: 'COMPONENTS', kind: 'component', status: 'CANDIDATE', searchText: 'Checkbox checkbox COMPONENTS component' },
  { id: 'radio', path: 'components/radio', label: 'Radio', icon: 'pi-circle', group: 'COMPONENTS', kind: 'component', status: 'CANDIDATE', searchText: 'Radio radio COMPONENTS component' },
  { id: 'toggle', path: 'components/toggle', label: 'Toggle / Switch', icon: 'pi-power-off', group: 'COMPONENTS', kind: 'component', status: 'CANDIDATE', searchText: 'Toggle / Switch toggle COMPONENTS component' },
  { id: 'segmented-control', path: 'components/segmented-control', label: 'Segmented Control', icon: 'pi-table', group: 'COMPONENTS', kind: 'component', status: 'CANDIDATE', searchText: 'Segmented Control segmented-control COMPONENTS component' },
  { id: 'status-badges', path: 'components/status-badges', label: 'Status & Badges', icon: 'pi-tag', group: 'COMPONENTS', kind: 'component', status: 'CANDIDATE', searchText: 'Status & Badges status-badges COMPONENTS component' },
  { id: 'alerts-feedback', path: 'components/alerts-feedback', label: 'Alerts & Feedback', icon: 'pi-bell', group: 'COMPONENTS', kind: 'component', status: 'CANDIDATE', searchText: 'Alerts & Feedback alerts-feedback COMPONENTS component' },
  { id: 'menus', path: 'components/menus', label: 'Menus & Action Menus', icon: 'pi-list', group: 'COMPONENTS', kind: 'component', status: 'CANDIDATE', searchText: 'Menus & Action Menus menus COMPONENTS component' },
  { id: 'tooltips', path: 'components/tooltips', label: 'Tooltips', icon: 'pi-question-circle', group: 'COMPONENTS', kind: 'component', status: 'CANDIDATE', searchText: 'Tooltips tooltips COMPONENTS component' },
  { id: 'dialogs-overlays', path: 'components/dialogs-overlays', label: 'Dialogs & Overlays', icon: 'pi-window-maximize', group: 'COMPONENTS', kind: 'component', status: 'CANDIDATE', searchText: 'Dialogs & Overlays dialogs-overlays COMPONENTS component' },
  { id: 'cards-surfaces', path: 'components/cards-surfaces', label: 'Cards & Surfaces', icon: 'pi-stop', group: 'COMPONENTS', kind: 'component', status: 'CANDIDATE', searchText: 'Cards & Surfaces cards-surfaces COMPONENTS component' },
  { id: 'lists-tables', path: 'components/lists-tables', label: 'Lists & Tables', icon: 'pi-table', group: 'COMPONENTS', kind: 'component', status: 'CANDIDATE', searchText: 'Lists & Tables lists-tables COMPONENTS component' },
  { id: 'progress-indicators', path: 'components/progress-indicators', label: 'Progress Indicators', icon: 'pi-spinner', group: 'COMPONENTS', kind: 'component', status: 'CANDIDATE', searchText: 'Progress Indicators progress-indicators COMPONENTS component' },
  { id: 'workflow-steps', path: 'components/workflow-steps', label: 'Workflow Steps', icon: 'pi-sitemap', group: 'COMPONENTS', kind: 'component', status: 'CANDIDATE', searchText: 'Workflow Steps workflow-steps COMPONENTS component' },
  { id: 'numeric-stepper', path: 'components/numeric-stepper', label: 'Numeric Stepper', icon: 'pi-plus-minus', group: 'COMPONENTS', kind: 'component', status: 'CANDIDATE', searchText: 'Numeric Stepper numeric-stepper COMPONENTS component' },
  { id: 'slider', path: 'components/slider', label: 'Slider', icon: 'pi-sliders-h', group: 'COMPONENTS', kind: 'component', status: 'CANDIDATE', searchText: 'Slider slider COMPONENTS component' },
  { id: 'navigation-sidebars', path: 'components/navigation-sidebars', label: 'Navigation & Sidebars', icon: 'pi-bars', group: 'COMPONENTS', kind: 'component', status: 'FROZEN', searchText: 'Navigation & Sidebars navigation-sidebars COMPONENTS component' },
  { id: 'forms', path: 'patterns/forms', label: 'Forms', icon: 'pi-file-edit', group: 'PATTERNS', kind: 'pattern', status: 'CANDIDATE', searchText: 'Forms forms PATTERNS pattern' },
  { id: 'search-filtering', path: 'patterns/search-filtering', label: 'Search & Filtering', icon: 'pi-filter', group: 'PATTERNS', kind: 'pattern', status: 'CANDIDATE', searchText: 'Search & Filtering search-filtering PATTERNS pattern' },
  { id: 'async-operations', path: 'patterns/async-operations', label: 'Async Operations', icon: 'pi-sync', group: 'PATTERNS', kind: 'pattern', status: 'CANDIDATE', searchText: 'Async Operations async-operations PATTERNS pattern' },
  { id: 'empty-loading-error', path: 'patterns/empty-loading-error', label: 'Empty / Loading / Error', icon: 'pi-inbox', group: 'PATTERNS', kind: 'pattern', status: 'CANDIDATE', searchText: 'Empty / Loading / Error empty-loading-error PATTERNS pattern' },
  { id: 'authentication', path: 'patterns/authentication', label: 'Authentication', icon: 'pi-lock', group: 'PATTERNS', kind: 'pattern', status: 'CANDIDATE', searchText: 'Authentication authentication PATTERNS pattern' },
  { id: 'legal-content', path: 'patterns/legal-content', label: 'Legal Content', icon: 'pi-file', group: 'PATTERNS', kind: 'pattern', status: 'CANDIDATE', searchText: 'Legal Content legal-content PATTERNS pattern' },
  { id: 'payments', path: 'patterns/payments', label: 'Payments', icon: 'pi-credit-card', group: 'PATTERNS', kind: 'pattern', status: 'CANDIDATE', searchText: 'Payments payments PATTERNS pattern' },
  { id: 'analytics', path: 'patterns/analytics', label: 'Analytics', icon: 'pi-chart-bar', group: 'PATTERNS', kind: 'pattern', status: 'CANDIDATE', searchText: 'Analytics analytics PATTERNS pattern' },
  { id: 'dispatch-board', path: 'patterns/dispatch-board', label: 'Dispatch Board', icon: 'pi-truck', group: 'PATTERNS', kind: 'pattern', status: 'CANDIDATE', searchText: 'Dispatch Board dispatch-board PATTERNS pattern' },
  { id: 'data-dense-operations', path: 'patterns/data-dense-operations', label: 'Data-Dense Operations', icon: 'pi-table', group: 'PATTERNS', kind: 'pattern', status: 'CANDIDATE', searchText: 'Data-Dense Operations data-dense-operations PATTERNS pattern' },
  { id: 'responsive', path: 'patterns/responsive', label: 'Responsive Composition', icon: 'pi-mobile', group: 'PATTERNS', kind: 'pattern', status: 'CANDIDATE', searchText: 'Responsive Composition responsive PATTERNS pattern' },
  { id: 'accessibility-lab', path: 'quality/accessibility-lab', label: 'Accessibility Lab', icon: 'pi-shield', group: 'QUALITY', kind: 'quality', status: 'CANDIDATE', searchText: 'Accessibility Lab accessibility-lab QUALITY quality' },
  { id: 'contrast-lab', path: 'quality/contrast-lab', label: 'Contrast Lab', icon: 'pi-eye', group: 'QUALITY', kind: 'quality', status: 'CANDIDATE', searchText: 'Contrast Lab contrast-lab QUALITY quality' },
  { id: 'heuristics', path: 'quality/heuristics', label: 'Nielsen Heuristics', icon: 'pi-check-circle', group: 'QUALITY', kind: 'quality', status: 'CANDIDATE', searchText: 'Nielsen Heuristics heuristics QUALITY quality' },
  { id: 'input-modality', path: 'quality/input-modality', label: 'Input Modality', icon: 'pi-keyboard', group: 'QUALITY', kind: 'quality', status: 'CANDIDATE', searchText: 'Input Modality input-modality QUALITY quality' },
  { id: 'component-maturity', path: 'quality/component-maturity', label: 'Component Maturity', icon: 'pi-bookmark', group: 'QUALITY', kind: 'quality', status: 'CANDIDATE', searchText: 'Component Maturity component-maturity QUALITY quality' },
  { id: 'angular-architecture', path: 'engineering/angular-architecture', label: 'Angular Architecture', icon: 'pi-sitemap', group: 'ENGINEERING', kind: 'engineering', status: 'CANDIDATE', searchText: 'Angular Architecture angular-architecture ENGINEERING engineering' },
  { id: 'design-tokens', path: 'engineering/design-tokens', label: 'Design Tokens', icon: 'pi-sliders-h', group: 'ENGINEERING', kind: 'engineering', status: 'CANDIDATE', searchText: 'Design Tokens design-tokens ENGINEERING engineering' },
  { id: 'component-apis', path: 'engineering/component-apis', label: 'Component APIs', icon: 'pi-code', group: 'ENGINEERING', kind: 'engineering', status: 'CANDIDATE', searchText: 'Component APIs component-apis ENGINEERING engineering' },
  { id: 'testing', path: 'engineering/testing', label: 'Testing', icon: 'pi-check-square', group: 'ENGINEERING', kind: 'engineering', status: 'CANDIDATE', searchText: 'Testing testing ENGINEERING engineering' },
  { id: 'figma-mapping', path: 'engineering/figma-mapping', label: 'Figma Mapping', icon: 'pi-pencil', group: 'ENGINEERING', kind: 'engineering', status: 'CANDIDATE', searchText: 'Figma Mapping figma-mapping ENGINEERING engineering' },
];

export const DOCUMENTATION_GROUPS: readonly DocumentationGroup[] = [
  { label: 'START HERE', items: DOCUMENTATION_PAGE_METADATA.filter((page) => page.group === 'START HERE') },
  { label: 'FOUNDATIONS', items: DOCUMENTATION_PAGE_METADATA.filter((page) => page.group === 'FOUNDATIONS') },
  { label: 'COMPONENTS', items: DOCUMENTATION_PAGE_METADATA.filter((page) => page.group === 'COMPONENTS') },
  { label: 'PATTERNS', items: DOCUMENTATION_PAGE_METADATA.filter((page) => page.group === 'PATTERNS') },
  { label: 'QUALITY', items: DOCUMENTATION_PAGE_METADATA.filter((page) => page.group === 'QUALITY') },
  { label: 'ENGINEERING', items: DOCUMENTATION_PAGE_METADATA.filter((page) => page.group === 'ENGINEERING') },
];
export const ALL_DOCUMENTATION_PAGE_METADATA = DOCUMENTATION_PAGE_METADATA;
