export type DocumentationKind =
  | 'overview'
  | 'principles'
  | 'foundation'
  | 'component'
  | 'pattern'
  | 'quality'
  | 'engineering'
  | 'reference';

export type DocumentationStatus = 'CANDIDATE' | 'EXPERIMENTAL' | 'LEGACY REFERENCE' | 'DEPRECATED';

export interface DocumentationPage {
  readonly id: string;
  readonly path: string;
  readonly label: string;
  readonly icon: string;
  readonly group: string;
  readonly kind: DocumentationKind;
  readonly eyebrow: string;
  readonly title: string;
  readonly intro: string;
  readonly summary: string;
  readonly status: DocumentationStatus;
  readonly keywords: readonly string[];
  readonly vueEvidence: string;
  readonly angularUsage: string;
  readonly figma: string;
}

export interface DocumentationGroup {
  readonly label: string;
  readonly items: readonly DocumentationPage[];
}

const page = (
  id: string,
  path: string,
  label: string,
  icon: string,
  group: string,
  kind: DocumentationKind,
  eyebrow: string,
  title: string,
  intro: string,
  summary: string,
  keywords: readonly string[],
  vueEvidence: string,
  angularUsage: string,
  figma: string,
  status: DocumentationStatus = 'CANDIDATE',
): DocumentationPage => ({
  id,
  path,
  label,
  icon,
  group,
  kind,
  eyebrow,
  title,
  intro,
  summary,
  status,
  keywords,
  vueEvidence,
  angularUsage,
  figma,
});

export const DOCUMENTATION_GROUPS: readonly DocumentationGroup[] = [
  {
    label: 'START HERE',
    items: [
      page(
        'overview',
        'overview',
        'Overview',
        'pi-th-large',
        'START HERE',
        'overview',
        '00 / START HERE',
        'A living Nexa design documentation system',
        'A navigable source of visual, interaction and implementation decisions for the Design Lab.',
        'Start with the decision boundary, then move from foundations to components, patterns and quality gates.',
        ['design system', 'documentation', 'orientation', 'v0.6'],
        'Vue/FLOW establish visual evidence; this page records the v0.6 documentation boundary.',
        'Standalone Angular documentation route; no production contract.',
        'Frame: `Documentation / Overview`; status badge: `CANDIDATE`.',
      ),
      page(
        'principles',
        'principles',
        'Design Principles',
        'pi-compass',
        'START HERE',
        'principles',
        '01 / PRINCIPLES',
        'Nexa is operational clarity with a human visual voice',
        'Principles protect domain meaning, hierarchy and trust before a component is styled.',
        'Use the smallest visual language that helps Sales, Buyer Portal and Operations make the next correct decision.',
        ['principles', 'clarity', 'hierarchy', 'trust'],
        'Observed in the Vue dashboard and portal: context first, action second, status alongside the object.',
        'Encode principles as reusable tokens, content rules and interaction tests.',
        'Frame: `Principles`; 5 principle cards; evidence footnotes.',
      ),
    ],
  },
  {
    label: 'FOUNDATIONS',
    items: [
      page(
        'color',
        'foundations/color',
        'Color',
        'pi-palette',
        'FOUNDATIONS',
        'foundation',
        'F1 / COLOR',
        'Color communicates responsibility, state and temperature',
        'Blue is the Nexa anchor. Supporting hues have a job; they are not decoration or a rainbow.',
        'Use semantic color with text, icons, shape or position so the meaning survives without color perception.',
        ['color', 'blue', 'semantic', 'contrast', 'status', 'OKLCH'],
        'Vue tokens: blue 50–900, slate, green, amber, red, orange, sky and indigo; workflow and cold-chain roles are separate.',
        'Use semantic CSS custom properties; test contrast and non-color cues at component level.',
        'Variables: `color.brand.action`; modes: light / high contrast; no automatic dark approval.',
      ),
      page(
        'typography',
        'foundations/typography',
        'Typography',
        'pi-align-left',
        'FOUNDATIONS',
        'foundation',
        'F2 / TYPOGRAPHY',
        'Type carries the operational hierarchy',
        'Plus Jakarta Sans gives Nexa its display voice; Inter carries dense UI work; JetBrains Mono identifies records.',
        'Hierarchy must remain legible at larger text sizes and in long identifiers, tables and forms.',
        ['typography', 'Plus Jakarta Sans', 'Inter', 'JetBrains Mono', 'type roles'],
        'Vue tokens and CSS use Plus Jakarta, Inter and JetBrains Mono with strong display weights and readable secondary text.',
        'Define roles as tokens and use native headings/labels; avoid one-off font declarations in feature templates.',
        'Text styles: Display, Large Title, Title, Heading, Subheading, Body, Callout, Label, Caption, Code.',
      ),
      page(
        'materials',
        'foundations/materials',
        'Materials & Surfaces',
        'pi-stop',
        'FOUNDATIONS',
        'foundation',
        'F3 / MATERIALS',
        'Surfaces establish a quiet operational plane',
        'Canvas, cards, selected rows, popovers and dialogs each have an explicit role, border and elevation.',
        'White principal work surfaces sit on a cool canvas; shadow is reserved for overlays and transient layers.',
        ['materials', 'surfaces', 'canvas', 'card', 'dialog', 'Liquid Glass'],
        'Vue uses white cards on `#F6FAFF` / `#F8FAFC`, structural borders and restrained overlay shadow; auth is a separate visual composition.',
        'Use surface tokens; never infer nesting from shadow alone. Liquid Glass remains experimental and outside dashboard content.',
        'Surface variables: Canvas, Primary, Grouped, Card, Selected, Raised, Menu, Dialog, Scrim.',
      ),
      page(
        'layout-spacing',
        'foundations/layout-spacing',
        'Layout & Spacing',
        'pi-arrows-alt',
        'FOUNDATIONS',
        'foundation',
        'F4 / LAYOUT',
        'A 4px rhythm makes density deliberate',
        'Align page headers, work surfaces, controls and data columns to a small set of repeatable intervals.',
        'Use 4px primitives and 8/12/16/24/32/48px applications; preserve gutters before shrinking type.',
        ['layout', 'spacing', '4px', 'autolayout', 'gutter'],
        'Vue shell: 240–284px navigation, 56–60px topbar, 16–40px page gutters, 8px nav rows and 12–16px panels.',
        'Use CSS grid/flex with minmax and intrinsic sizing; document overflow for data instead of hiding columns.',
        'Auto Layout: page stack, toolbar cluster, panel header, table row, responsive gutter tokens.',
      ),
      page(
        'shape-radius',
        'foundations/shape-radius',
        'Shape & Radius',
        'pi-stop-circle',
        'FOUNDATIONS',
        'foundation',
        'F5 / SHAPE',
        'Soft geometry, no default pill language',
        'Nexa uses rounded rectangles for work surfaces and compact controls; full pills belong to badges and compact status.',
        'The full-capsule navigation decision is revoked. The Vue `.nav-item` evidence is approximately 8px.',
        ['shape', 'radius', '8px', 'rounded', 'pill'],
        'Vue/Flow active nav: pale-blue rounded rectangle with a slim blue inset edge, approximately 8px radius.',
        'Use semantic radii: control 8–10px, card 12–16px, overlay 16–18px, pill only where content is compact.',
        'Radius variables mapped to component properties; no `9999px` for navigation.',
      ),
      page(
        'iconography',
        'foundations/iconography',
        'Iconography',
        'pi-compass',
        'FOUNDATIONS',
        'foundation',
        'F6 / ICONOGRAPHY',
        'PrimeIcons support the label',
        'Icons are line-weighted, quiet and optically aligned. They clarify action or state; they do not compete with Nexa content.',
        'Prefer the observed Vue PrimeIcons family and consistent 16–20px sizes over expressive icon packs.',
        ['iconography', 'PrimeIcons', 'optical alignment', 'icon-only'],
        'Vue uses PrimeIcons such as `pi-th-large`, `pi-box`, `pi-inbox`, `pi-truck`, `pi-bell` and `pi-sign-out`.',
        'Render decorative icons `aria-hidden`; give icon-only buttons accessible names and a 44px visual/hit-area contract.',
        'Icon property: name, size, stroke/weight, label relationship, state color, accessible name.',
      ),
      page(
        'motion',
        'foundations/motion',
        'Motion',
        'pi-bolt',
        'FOUNDATIONS',
        'foundation',
        'F7 / MOTION',
        'Motion explains a state change',
        'Use short transitions for hover, press, disclosure and overlay entry; never animate to make a static page feel alive.',
        'Every transition needs a cause, a changed state and a continuity cue.',
        ['motion', 'reduced motion', 'transition', 'loading', 'disclosure'],
        'Vue uses short 140–250ms transitions and route fade patterns; long decorative motion is not a visual contract.',
        'Use CSS transitions with `prefers-reduced-motion`; keep loading and progress semantics visible in text.',
        'Motion tokens: duration, easing, property, reduced-motion fallback, interruption behavior.',
      ),
    ],
  },
  {
    label: 'COMPONENTS',
    items: [
      page(
        'buttons',
        'components/buttons',
        'Buttons',
        'pi-external-link',
        'COMPONENTS',
        'component',
        'C1 / BUTTONS',
        'Buttons make one next action obvious',
        'Primary, secondary, quiet, destructive and icon-only actions share a clear label and state contract.',
        'Choose by consequence and hierarchy, not by visual preference.',
        ['button', 'action', 'primary', 'secondary', 'loading', 'disabled'],
        'Vue actions use blue primary buttons, pale-blue secondary actions and restrained neutral controls.',
        'Use native `<button>` with explicit `type`; Angular wrappers may add loading/pressed state without changing semantics.',
        'Properties: label, intent, size, icon, loading, disabled, fullWidth, type.',
      ),
      page(
        'text-fields',
        'components/text-fields',
        'Text Fields',
        'pi-pencil',
        'COMPONENTS',
        'component',
        'C2 / TEXT FIELDS',
        'Text fields make input and recovery visible',
        'Labels, help, error and value state remain connected and readable without relying on placeholder text.',
        'Use for one value; use search fields for find-as-you-type tasks and select/combo for constrained choices.',
        ['text field', 'input', 'label', 'error', 'helper'],
        'Vue auth and registration forms use labeled bordered fields, helper text and inline red recovery guidance.',
        'Native inputs plus Angular forms; `aria-describedby` owns help/error; preserve user input on recoverable errors.',
        'Properties: label, value, placeholder, help, error, required, disabled, readOnly, inputMode.',
      ),
      page(
        'search-fields',
        'components/search-fields',
        'Search Fields',
        'pi-search',
        'COMPONENTS',
        'component',
        'C3 / SEARCH',
        'Search finds a known object quickly',
        'Search input has a visible label, clear affordance when populated and result status.',
        'Do not use search to hide a small static set or replace a filter with known categories.',
        ['search', 'filter', 'query', 'clear', 'results'],
        'Vue catalog and order flows use search/filter controls near the content they change.',
        'Use `type="search"`, an explicit label and live result status; debounce only when the product contract calls for it.',
        'Properties: query, scope, placeholder, clearable, loading, resultCount, emptyMessage.',
      ),
      page(
        'select-combo',
        'components/select-combo',
        'Select & Combo Box',
        'pi-chevron-down',
        'COMPONENTS',
        'component',
        'C4 / SELECTION',
        'Selection controls expose the available vocabulary',
        'Native select is the baseline; combobox is reserved for searchable or large option sets.',
        'Do not style a plain button as a select without keyboard, popup and value semantics.',
        ['select', 'combo box', 'listbox', 'option', 'filter'],
        'Vue registration and workspace forms use native selects for bounded choices; no custom menu is needed for every field.',
        'Prefer native `<select>`; use Angular Aria/CDK only when behavior complexity warrants it.',
        'Properties: label, options, value, multiple, searchable, invalid, disabled, popup placement.',
      ),
      page(
        'selection',
        'components/selection',
        'Checkbox / Radio / Toggle',
        'pi-check-square',
        'COMPONENTS',
        'component',
        'C5 / SELECTION',
        'Selection answers one clear question',
        'Checkboxes allow independent choices, radios choose one value, toggles change an immediate setting.',
        'Do not use toggle styling for a deferred submit or a multi-step choice that needs confirmation.',
        ['checkbox', 'radio', 'toggle', 'checked', 'indeterminate'],
        'Vue flows show checked/selected states through blue fills, pale surfaces and supporting labels.',
        'Use native input semantics or Angular Aria patterns; keep group labels and error ownership explicit.',
        'Properties: groupLabel, options, checked, mixed, disabled, describedBy, orientation.',
      ),
      page(
        'status-badges',
        'components/status-badges',
        'Status & Badges',
        'pi-tag',
        'COMPONENTS',
        'component',
        'C6 / STATUS',
        'Status is text first, color second',
        'Badges compactly identify workflow, priority, role or temperature without blending those vocabularies.',
        'Do not use a badge for a sentence, an action or a metric that needs context.',
        ['status', 'badge', 'priority', 'temperature', 'semantic'],
        'Vue uses compact blue/green/amber/red status treatments and separate temperature/priority badges.',
        'Provide readable text and an icon/shape cue where color is meaningful; status changes use `aria-live` only when appropriate.',
        'Properties: semantic, label, icon, dot, temperature, priority, compact.',
      ),
      page(
        'alerts-feedback',
        'components/alerts-feedback',
        'Alerts & Feedback',
        'pi-info-circle',
        'COMPONENTS',
        'component',
        'C7 / FEEDBACK',
        'Feedback tells users what happened and what to do',
        'Inline banners, alerts, toasts and empty states differ by urgency, persistence and actionability.',
        'Do not turn every successful click into a toast; inline feedback belongs beside the affected content.',
        ['alert', 'banner', 'toast', 'empty', 'error', 'success'],
        'Vue registration and auth expose info/error banners with explanatory copy and recovery path.',
        'Use `role="alert"` for urgent errors, `role="status"` for non-urgent changes and preserve focus after failures.',
        'Properties: tone, title, message, action, dismissible, liveRegion, persistence.',
      ),
      page(
        'menus',
        'components/menus',
        'Menus & Action Menus',
        'pi-bars',
        'COMPONENTS',
        'component',
        'C8 / MENUS',
        'Menus group secondary actions without stealing context',
        'Menus are for commands; navigation uses links; selection uses listbox/select.',
        'Keep the trigger label stable and place destructive actions last and separated.',
        ['menu', 'action menu', 'escape', 'arrow keys', 'overlay'],
        'Vue notification, mobile and workflow surfaces use explicit buttons and compact action groups.',
        'Use Angular Aria or CDK overlay for roving keyboard focus, Escape and focus return; document placement and collision.',
        'Properties: trigger, items, groups, disabled, destructive, shortcut, placement, closeOnSelect.',
      ),
      page(
        'tooltips',
        'components/tooltips',
        'Tooltips',
        'pi-question-circle',
        'COMPONENTS',
        'component',
        'C9 / TOOLTIPS',
        'Tooltips explain unfamiliar controls, not core instructions',
        'A tooltip is supplemental and delay-based; a label or helper text is required for essential meaning.',
        'Do not put required content or error recovery only in a hover tooltip.',
        ['tooltip', 'help', 'hover', 'focus', 'touch'],
        'Vue uses visible labels beside primary actions; icons are not expected to carry all meaning alone.',
        'Support keyboard focus and touch-safe disclosure; avoid trapping focus or relying on hover alone.',
        'Properties: content, placement, trigger, delay, describedTarget, interactive.',
      ),
      page(
        'overlays',
        'components/overlays',
        'Dialogs & Overlays',
        'pi-window-maximize',
        'COMPONENTS',
        'component',
        'C10 / OVERLAYS',
        'Overlays focus a decision without losing the place',
        'Dialogs, drawers and popovers have focus ownership, scrim, Escape and restoration rules.',
        'Use an overlay only when the task benefits from preserving the underlying context.',
        ['dialog', 'drawer', 'popover', 'scrim', 'focus restoration'],
        'Vue cart drawer, notifications and request modal use white overlay surfaces with restrained shadow.',
        'Use CDK Overlay or Angular Aria patterns; inert the background and return focus to the invoking control.',
        'Properties: modal, title, close, size, placement, scroll, initialFocus, returnFocus.',
      ),
      page(
        'lists-tables',
        'components/lists-tables',
        'Lists & Tables',
        'pi-table',
        'COMPONENTS',
        'component',
        'C11 / DATA DISPLAY',
        'Data display preserves comparison and object identity',
        'Use semantic tables for columns and lists for repeated objects; wrap before changing meaning on narrow screens.',
        'Do not turn every row into a card if comparison or scan order matters.',
        ['table', 'list', 'row', 'column', 'overflow'],
        'Vue Sales and Logistics screens use dense columns, identifiers, status and row actions with white work surfaces.',
        'Use native table semantics, caption/headers and local horizontal scroll; keep a compact mobile alternative only when documented.',
        'Properties: columns, density, sortable, selectable, empty, loading, rowAction, overflow.',
      ),
      page(
        'progress-steppers',
        'components/progress-steppers',
        'Progress & Steppers',
        'pi-chart-line',
        'COMPONENTS',
        'component',
        'C12 / PROGRESS',
        'Progress locates work in a known sequence',
        'Steppers show phase and permission to move; progress indicators show ongoing work.',
        'Do not imply business completion from a visual animation or invent a progress percentage.',
        ['progress', 'stepper', 'wizard', 'loading', 'phase'],
        'FLOW registration and buyer order tracking use numbered steps with one active state and readable labels.',
        'Expose current step, completed state and next/back actions; provide a text equivalent for indeterminate progress.',
        'Properties: steps, current, completed, disabled, orientation, label, date, linear.',
      ),
      page(
        'navigation-sidebars',
        'components/navigation-sidebars',
        'Navigation & Sidebars',
        'pi-th-large',
        'COMPONENTS',
        'component',
        'C13 / NAVIGATION',
        'Navigation makes location and scope obvious',
        'The sidebar is persistent on desktop and a drawer on mobile; active rows reflect the current route.',
        'Do not use a decorative rail or full capsule without Vue/FLOW evidence.',
        ['navigation', 'sidebar', 'active', 'drawer', 'current'],
        'Vue ops sidebar is white, grouped, 240–284px wide, PrimeIcons, 8px active row and a pale-blue selection surface.',
        'Use router links with `aria-current`; disclosure groups support keyboard and focus restoration on mobile.',
        'Properties: group, item, active, badge, disclosure, persistence, drawer state.',
      ),
      page(
        'cards-panels',
        'components/cards-panels',
        'Cards & Panels',
        'pi-stop',
        'COMPONENTS',
        'component',
        'C14 / SURFACES',
        'Panels give related operational facts a boundary',
        'Use a panel when content shares a heading, action or state; use a card for a discrete object or choice.',
        'Do not wrap every paragraph in a card or stack identical cards without hierarchy.',
        ['card', 'panel', 'surface', 'header', 'empty'],
        'Vue dashboards use panel headers, structural borders, white surfaces and action alignment.',
        'Use semantic section headings and consistent padding; no elevation is necessary for a resting panel.',
        'Properties: surface, title, subtitle, action, padding, divider, density, state.',
      ),
    ],
  },
  {
    label: 'PATTERNS',
    items: [
      page(
        'forms',
        'patterns/forms',
        'Forms',
        'pi-list',
        'PATTERNS',
        'pattern',
        'P1 / FORMS',
        'Forms make the next valid step clear',
        'Labels, grouping, validation, required status and recovery are designed as one flow.',
        'A form should explain what is needed before the user submits and preserve safe input after errors.',
        ['form', 'validation', 'input', 'error', 'submit'],
        'Vue auth/register and manual-order flows use grouped fields, helper copy, visible errors and back/next actions.',
        'Use Angular reactive forms or signal-based forms with native controls and explicit error summaries where needed.',
        'Flow: context → grouped fields → inline validation → review → safe commit.',
      ),
      page(
        'search-filtering',
        'patterns/search-filtering',
        'Search & Filtering',
        'pi-filter',
        'PATTERNS',
        'pattern',
        'P2 / SEARCH',
        'Find, narrow and clear without losing context',
        'Search is for known objects; filters narrow a result set and retain visible applied state.',
        'Show active filters, count or empty explanation and a clear route back to the full set.',
        ['search', 'filter', 'query', 'empty', 'clear'],
        'Vue catalog and request inbox place controls before the content they change.',
        'Keep filter state in route/query state when deep links matter; announce result updates without noisy live regions.',
        'Flow: query → filters → applied state → result count → empty/recovery.',
      ),
      page(
        'workflows',
        'patterns/workflows',
        'Workflows & Wizards',
        'pi-share-alt',
        'PATTERNS',
        'pattern',
        'P3 / WORKFLOW',
        'Manual Order Entry is a guided operational decision',
        'Select client, choose products, confirm conditions, arrange delivery and review before commit.',
        'Each phase has a single current state, a safe back path and a truthful completion message.',
        ['wizard', 'manual order', 'review', 'back', 'next'],
        'Vue route: `/ops/commercial/manual-order-entry` → `create-order-view.vue`; FLOW contains the phase 1–4 golden screens.',
        'Compose shared stepper, client selection, product rows and review panels without inventing API state.',
        'Flow mapping: client → catalog → conditions → delivery → review; properties map per phase.',
      ),
      page(
        'dashboards',
        'patterns/dashboards',
        'Dashboards & Analytics',
        'pi-chart-bar',
        'PATTERNS',
        'pattern',
        'P4 / DASHBOARD',
        'Dashboards prioritize work, not decoration',
        'A dashboard starts with context, actionable workload, status and the next useful action.',
        'Metrics must earn their space and retain a source, unit and time context.',
        ['dashboard', 'KPI', 'analytics', 'workload', 'panel'],
        'Vue sales dashboard: action banner, four status cards, request/doc panels, credit cases and quick actions.',
        'Use grid areas and semantic headings; do not introduce generic bento layouts or fake metrics.',
        'Layout: page header → action banner → workload cards → operational panels → next actions.',
      ),
      page(
        'states',
        'patterns/states',
        'Empty / Loading / Error',
        'pi-refresh',
        'PATTERNS',
        'pattern',
        'P5 / STATES',
        'States are content, not placeholders',
        'Empty, loading, error, success and read-only states answer what happened and what can happen next.',
        'Skeleton loaders are not a default Nexa rule; use meaningful progress or stable layout when data loading is shown.',
        ['empty', 'loading', 'error', 'success', 'read-only'],
        'Vue uses empty panels, inline banners and button recovery; no universal skeleton treatment is established.',
        'Use `role="status"` only for meaningful updates; preserve stable headings and accessible recovery actions.',
        'State matrix: default, loading, empty, error, success, read-only; meaningful combinations only.',
      ),
      page(
        'authentication',
        'patterns/authentication',
        'Authentication',
        'pi-lock',
        'PATTERNS',
        'pattern',
        'P6 / AUTH',
        'Authentication is a calm, high-confidence gate',
        'Workspace discovery, corporate email and password are explicit steps with recoverable errors.',
        'Auth may use a distinctive blue composition; do not generalize its special treatment to dashboards.',
        ['auth', 'login', 'workspace', 'password', 'error'],
        'FLOW login: split blue brand panel / white form plane, workspace preview, corporate email, password and clear error path.',
        'Use native forms, labels, password visibility affordance and no credential invention in the Design Lab.',
        'Frame: split composition; form fields map to workspace, email, password, recovery and register.',
      ),
      page(
        'responsive',
        'patterns/responsive',
        'Responsive Composition',
        'pi-mobile',
        'PATTERNS',
        'pattern',
        'P7 / RESPONSIVE',
        'Responsive means preserving the task',
        'Desktop, tablet and mobile change composition, not meaning, vocabulary or affordances.',
        'At 320px/400% zoom, text and controls reflow; dense tables may scroll locally when two-dimensional comparison is essential.',
        ['responsive', 'mobile', 'tablet', 'reflow', 'zoom'],
        'Vue hides persistent sidebars at narrow widths, adds mobile menus/bottom nav and keeps action labels available.',
        'Test 1440px, 1024px, 768px and 390px; define hit area separately from visible icon size.',
        'Breakpoints map shell, grid, table overflow, drawer, bottom navigation and type scaling.',
      ),
    ],
  },
  {
    label: 'QUALITY',
    items: [
      page(
        'accessibility',
        'quality/accessibility',
        'Accessibility',
        'pi-universal-access',
        'QUALITY',
        'quality',
        'Q1 / ACCESSIBILITY',
        'Accessibility is part of every visual contract',
        'WCAG 2.2 AA is the target for design and implementation review; this candidate is not certification.',
        'Semantics, focus, keyboard, contrast, non-color cues, reflow, target size and reduced motion are documented beside components.',
        ['accessibility', 'WCAG 2.2', 'keyboard', 'focus', 'contrast'],
        'Vue has labels, roles and responsive adaptations but requires matched Angular runtime testing before parity claims.',
        'Use native semantics, Angular Aria/CDK where needed and manual keyboard/AT checks; record evidence separately from build health.',
        'Checklist component: criterion, visual behavior, keyboard behavior, screen-reader name, test evidence.',
      ),
      page(
        'heuristics',
        'quality/heuristics',
        'Nielsen Heuristics',
        'pi-search-plus',
        'QUALITY',
        'quality',
        'Q2 / HEURISTICS',
        'Nielsen turns visual polish into usable behavior',
        'The ten heuristics are applied to Documentation and Reference Screens with evidence, impact, severity and remediation.',
        'A violation is not an automatic redesign; context, task and the NN/G 0–4 severity method govern priority.',
        ['Nielsen', 'heuristics', 'severity', 'usability', 'audit'],
        'The audit uses Vue/FLOW as visual evidence and the rendered Angular Design Lab as implementation evidence.',
        'Keep findings actionable and route-specific; human review remains required.',
        'Audit row: heuristic, evidence, route, impact, severity, recommendation, status.',
      ),
      page(
        'input-modality',
        'quality/input-modality',
        'Responsive & Input Modality',
        'pi-keyboard',
        'QUALITY',
        'quality',
        'Q3 / INPUT',
        'Mouse, touch, keyboard and assistive tech share one task model',
        'Visual size and hit area are separate decisions; input modality changes affordance and focus treatment.',
        'No essential action is gesture-only, hover-only or color-only.',
        ['keyboard', 'mouse', 'touch', 'trackpad', 'assistive technology', 'hit area'],
        'Vue mobile menus and desktop sidebars provide separate compositions; PrimeIcons remain labels-supported.',
        'Test tab order, Escape, Enter/Space, arrow keys where patterned, touch target and screen-reader names.',
        'Interaction model: pointer, keyboard, touch, AT; component behavior notes per modality.',
      ),
    ],
  },
  {
    label: 'ENGINEERING',
    items: [
      page(
        'angular-compatibility',
        'engineering/angular-compatibility',
        'Angular Compatibility',
        'pi-code',
        'ENGINEERING',
        'engineering',
        'E1 / ANGULAR',
        'Behavior source and visual owner stay separate',
        'Angular Aria/CDK/Material can provide behavior primitives while Nexa owns the visual contract.',
        'The page is a compatibility matrix, not a Material showcase or a replacement for the design system.',
        ['Angular', 'Aria', 'CDK', 'Material', 'overlay', 'routing'],
        'Vue/PrimeVue is visual evidence; Angular 22 is the target implementation stack for this lab.',
        'Prefer standalone lazy routes, native semantics, Angular Aria for headless patterns and CDK Overlay for transient layers.',
        'Matrix fields: component, Nexa contract, behavior source, presentation owner, implementation/a11y status.',
      ),
      page(
        'design-tokens',
        'engineering/design-tokens',
        'Design Tokens',
        'pi-sliders-h',
        'ENGINEERING',
        'engineering',
        'E2 / TOKENS',
        'Tokens keep decisions reusable and reversible',
        'Primitive values feed semantic meaning; component tokens depend on semantics, never the reverse.',
        'A token name explains intent and can be mapped to Figma variables without hiding the underlying value.',
        ['tokens', 'primitive', 'semantic', 'component', 'Figma variables'],
        'Vue `tokens.css` is the extraction source; Angular semantic tokens normalize it without copying C# or backend concerns.',
        'Keep CSS variables scoped to design concerns, document fallback and avoid one-off literal values in specimens.',
        'Variable collections: Primitives, Semantic, Component; modes: Light, High Contrast candidate.',
      ),
      page(
        'figma-mapping',
        'engineering/figma-mapping',
        'Figma Mapping',
        'pi-pencil',
        'ENGINEERING',
        'engineering',
        'E3 / FIGMA',
        'A designer can reconstruct the same decision',
        'Figma mapping records names, properties, variables and states for future library work; it does not create a Figma file.',
        'Every component page lists property names, variants, state matrix and token dependencies.',
        ['Figma', 'handoff', 'properties', 'variables', 'states'],
        'Vue/FLOW provide specimen evidence; human designers still own final component naming and library publication.',
        'Use the mapping as a handoff contract, not generated production code.',
        'Property table + variable references + state coverage + open questions.',
      ),
      page(
        'component-coverage',
        'engineering/component-coverage',
        'Component Coverage',
        'pi-check-square',
        'ENGINEERING',
        'engineering',
        'E4 / COVERAGE',
        'Coverage makes gaps visible before implementation',
        'The inventory maps every requested component, current specimen, real Nexa usage and unresolved state.',
        'Coverage means documented, not approved or production-complete.',
        ['coverage', 'inventory', 'implementation', 'status', 'usage'],
        'Vue routes and FLOW names are mapped to actual Angular reference routes only where comparable evidence exists.',
        'Use route-level lazy loading for documentation and references; keep testable ownership boundaries.',
        'Coverage matrix: component, doc page, visual states, a11y, Angular implementation, real usage, status.',
      ),
    ],
  },
];

export const REFERENCE_GROUP: DocumentationGroup = {
  label: 'REFERENCE SCREENS',
  items: [
    page(
      'reference-platform',
      'reference/platform/dashboard',
      'Nexa Platform',
      'pi-building',
      'REFERENCE SCREENS',
      'reference',
      'R1 / PLATFORM',
      'Platform reference screen library',
      'Sales and Logistics compositions grounded in Vue/FLOW evidence and synthetic Design Lab data.',
      'Reference screens are visual comparison fixtures, not production routes or domain authority.',
      ['platform', 'sales', 'logistics', 'dashboard', 'catalog'],
      'Vue ops routes include commercial dashboard, purchase requests, manual order entry, purchase orders, clients and logistics.',
      'Angular reference routes are isolated in the Design Lab and use synthetic data.',
      'Reference frame: Platform shell, sidebar active row, route-specific surface composition.',
      'LEGACY REFERENCE',
    ),
    page(
      'reference-portal',
      'reference/portal/home',
      'Buyer Portal',
      'pi-shopping-bag',
      'REFERENCE SCREENS',
      'reference',
      'R2 / BUYER PORTAL',
      'Buyer Portal reference screen library',
      'Buyer-facing catalog, request builder, orders, payments and tracking compositions.',
      'The portal keeps a horizontal Vue navigation language distinct from the operations sidebar.',
      ['portal', 'buyer', 'catalog', 'request builder', 'tracking'],
      'Vue portal routes: home, request builder, purchase requests, purchase orders, profile, support and legal.',
      'Angular portal routes are synthetic and visually isolated from production.',
      'Reference frame: horizontal nav, buyer hero, metric cards, tracking panel.',
      'LEGACY REFERENCE',
    ),
    page(
      'reference-auth',
      'reference/auth/login',
      'Authentication',
      'pi-lock',
      'REFERENCE SCREENS',
      'reference',
      'R3 / AUTH',
      'Authentication reference screen library',
      'Login and workspace setup evidence from FLOW, preserved as a separate composition.',
      'Auth is intentionally more expressive than the calm operational shell; do not copy its gradients into dashboards.',
      ['auth', 'login', 'register', 'workspace'],
      'FLOW login/register show the split blue brand plane and white form plane.',
      'Angular auth references use synthetic content and remain Design Lab-only.',
      'Reference frame: split auth composition, workspace form and state coverage.',
      'LEGACY REFERENCE',
    ),
  ],
};

export const ALL_DOCUMENTATION_PAGES: readonly DocumentationPage[] = [
  ...DOCUMENTATION_GROUPS.flatMap((group) => group.items),
  ...REFERENCE_GROUP.items,
];

export const DOCUMENTATION_PAGE_MAP = new Map(
  ALL_DOCUMENTATION_PAGES.map((documentationPage) => [documentationPage.id, documentationPage]),
);

export const DOCUMENTATION_ROUTE_ALIASES: Readonly<Record<string, string>> = {
  foundations: 'foundations/color',
  components: 'components/buttons',
  patterns: 'patterns/forms',
  material: 'engineering/angular-compatibility',
};
