import type { DocumentationPageContent } from '../models/documentation-page';

export const ENGINEERING_CONTENT: readonly DocumentationPageContent[] = [
  {
    id: 'angular-architecture', label: 'Angular Architecture', icon: 'pi-sitemap', group: 'ENGINEERING', kind: 'engineering', eyebrow: 'E1 / ANGULAR', title: 'Feature areas stay understandable and lazy', intro: 'Standalone routes, focused shared components, signal-first state and strict template checks keep the lab maintainable.', summary: 'Documentation, specimens and reusable controls have separate responsibilities.', keywords: ['Angular', 'standalone', 'signals', 'lazy loading'], decision: 'No God Documentation component or giant presentation registry.', foundation: 'Token layers and small shared UI contracts.', angularContract: 'Angular 22, strict TypeScript, OnPush and native semantics. Analytics, Authentication and Dispatch Board load their own page features.', adoptionMapping: 'Component ownership and candidate properties are implementation evidence.'
  },
  {
    id: 'design-tokens', label: 'Design Tokens', icon: 'pi-sliders-h', group: 'ENGINEERING', kind: 'engineering', eyebrow: 'E2 / TOKENS', title: 'Primitive, semantic and component tokens form one dependency graph', intro: 'The token page shows actual relationships, state tokens and standard/increased contrast mode behavior.', summary: 'Magic values and arbitrary opacity hacks are rejected.', keywords: ['tokens', 'primitive', 'semantic', 'component', 'modes'], decision: 'Component tokens are added only when semantic intent is insufficient.', foundation: 'Blue, slate, support families, spacing, radius, motion and typography.', angularContract: 'Token integrity and contrast scripts run independently.', adoptionMapping: 'CSS custom properties map to future variable modes.'
  },
  {
    id: 'component-apis', label: 'Component APIs', icon: 'pi-code', group: 'ENGINEERING', kind: 'engineering', eyebrow: 'E3 / APIs', title: 'Candidate APIs are semantic and future-consumable', intro: 'Text Field, Button, Toggle, Segmented Control, Card and State Sequence contracts expose user-facing behavior.', summary: 'Specimen simulation never leaks into production component APIs.', keywords: ['API', 'input', 'output', 'model', 'harness'], decision: 'One concept per component; no universal field or box. Action Menu stays custom after the v0.10 KEEP-vs-REFINE spike; Tooltip keeps separate semantics.', foundation: 'Native semantics plus tokenized state relationships.', angularContract: 'input, output, model, computed and strict types.', adoptionMapping: 'Properties and states align with future component sets.'
  },
  {
    id: 'testing', label: 'Testing', icon: 'pi-check-square', group: 'ENGINEERING', kind: 'engineering', eyebrow: 'E4 / TESTING', title: 'Tests prove user-facing contracts', intro: 'Behavior, keyboard, disabled, model updates, accessible attributes, token integrity and contrast gates are explicit.', summary: 'No fragile implementation-class assertions as the primary proof.', keywords: ['tests', 'unit', 'harness', 'contrast', 'tokens'], decision: 'Coverage follows stable contracts, not raw count.', foundation: 'Shared components and utilities have focused tests.', angularContract: 'Angular unit tests plus deterministic Node gates.', adoptionMapping: 'Visual review evidence remains separate from automated tests.'
  },
  {
    id: 'design-adoption', label: 'Design Adoption & Handoff', icon: 'pi-briefcase', group: 'ENGINEERING', kind: 'engineering', eyebrow: 'E5 / ADOPTION', title: 'Design evidence becomes a consumable handoff', intro: 'Adoption records the public package, token source, maturity, ownership and validation evidence needed to move a candidate into a product application.', summary: 'Handoff is explicit; no fictional design-library publication is implied.', keywords: ['adoption', 'handoff', 'Angular', 'public API', 'ownership'], decision: 'Use the public Nexa UI entrypoint and attach evidence before product adoption.', foundation: 'Frozen visual direction plus candidate component contracts.', angularContract: 'Consumers import from nexa-ui; documentation and Lab-only evidence stay private.', adoptionMapping: 'No live Figma library is claimed; future mapping must reference the same public component contract.'
  },
];
