import type { DocumentationPageContent } from '../models/documentation-page';

export const FOUNDATIONS_CONTENT: readonly DocumentationPageContent[] = [
  {
    id: 'layout-spacing', label: 'Layout & Spacing', icon: 'pi-arrows-alt', group: 'FOUNDATIONS', kind: 'foundation', eyebrow: 'F4 / LAYOUT', title: 'A 4px rhythm makes density deliberate', intro: 'Padding, gutters, alignment and responsive reflow are shown as measurable layout evidence.', summary: 'Use intrinsic grid and flex layout before shrinking content.', keywords: ['layout', 'spacing', 'padding', 'responsive', 'reflow'], decision: 'A small spacing scale protects alignment across documentation and specimens.', foundation: '4px primitives become 8, 12, 16, 24, 32 and 48px applications.', angularContract: 'CSS grid/flex with minmax; wide matrices scroll locally when semantics require it.', adoptionMapping: 'Auto Layout contracts cover page stack, toolbar, panel, row and responsive gutter.'
  },
  {
    id: 'shape-radius', label: 'Shape & Radius', icon: 'pi-stop-circle', group: 'FOUNDATIONS', kind: 'foundation', eyebrow: 'F5 / SHAPE', title: 'Soft geometry without pill everything', intro: 'Radii are shown by responsibility: controls, cards, panels, overlays and compact status.', summary: 'Radius expresses hierarchy, not decoration.', keywords: ['shape', 'radius', 'card', 'control'], decision: 'Subtle rounded rectangles are canonical; full pills stay limited to compact status.', foundation: 'Semantic radii alias primitive values and remain consistent across states.', angularContract: 'Components own meaningful geometry; documentation wrappers do not leak APIs.', adoptionMapping: 'Radius variables map to component properties and layout surfaces.'
  },
  {
    id: 'surfaces', label: 'Surfaces', icon: 'pi-stop', group: 'FOUNDATIONS', kind: 'foundation', eyebrow: 'F6 / SURFACES', title: 'Surfaces create a calm operational plane', intro: 'Canvas, primary, grouped, selected, raised and overlay planes are rendered with explicit responsibility.', summary: 'White structural surfaces sit on a cool canvas; elevation stays meaningful.', keywords: ['surfaces', 'canvas', 'card', 'panel', 'overlay'], decision: 'Surface, Card and Panel are distinct concepts; no universal Box abstraction.', foundation: 'Surface tokens define plane; component borders, padding and radius define object grouping.', angularContract: 'NexaSurface is small and composable; docs primitives remain docs-only.', adoptionMapping: 'Surface roles map to fills, borders, radius and elevation variables.'
  },
  {
    id: 'iconography', label: 'Iconography', icon: 'pi-compass', group: 'FOUNDATIONS', kind: 'foundation', eyebrow: 'F7 / ICONOGRAPHY', title: 'Icons support labels and state', intro: 'PrimeIcons remain quiet, aligned and purposeful across navigation, actions and status evidence.', summary: 'Icon weight never competes with operational content.', keywords: ['icons', 'PrimeIcons', 'alignment', 'accessible name'], decision: 'Keep PrimeIcons as current candidate icon system.', foundation: '16–20px line icons, label relationships, state colors and non-color cues.', angularContract: 'Decorative icons are hidden; icon-only actions expose names and target geometry.', adoptionMapping: 'Icon name, size, weight, label relationship and state color are explicit properties.'
  },
  {
    id: 'motion', label: 'Motion', icon: 'pi-bolt', group: 'FOUNDATIONS', kind: 'foundation', eyebrow: 'F8 / MOTION', title: 'Motion explains a state change', intro: 'Live specimens show cause, changed state, duration, easing and reduced-motion behavior.', summary: 'No continuous decorative animation.', keywords: ['motion', 'transition', 'reduced motion', 'easing'], decision: 'Short feedback motion is allowed when it preserves context and has a reason.', foundation: '140–250ms semantic durations with tokenized easing and reduced fallback.', angularContract: 'CSS transitions plus prefers-reduced-motion; no animation dependency.', adoptionMapping: 'Motion entries expose trigger, property, duration, easing and fallback.'
  },
];

