import type { DocAnswer } from './documentation-data';

export const COMPONENT_GUIDANCE: Readonly<Record<string, readonly DocAnswer[]>> = {
  buttons: [
    { title: 'Anatomy', copy: 'Intent, label, optional icon, busy state and adjacent outcome form one activation contract.' },
    { title: 'States', copy: 'Rest, hover, focus, pressed, disabled, processing, success and failure stay geometrically stable.' },
    { title: 'Accessibility', copy: 'Use a native button for actions; a disabled or loading link must not navigate by pointer or keyboard.' },
    { title: 'Tokens', copy: 'Action intent uses semantic blue, quiet, danger and focus aliases; no state adds a hard corner.' },
    { title: 'Use it when', copy: 'There is one clear next action. Use a menu for commands and a segmented control for a small value choice.' },
  ],
  'text-fields': [
    { title: 'Anatomy', copy: 'Visible label, input, helper or error, optional leading/trailing action and current value remain associated.' },
    { title: 'States', copy: 'Empty, filled, focus, invalid, read-only, disabled and loading are separate field conditions.' },
    { title: 'Accessibility', copy: 'The label names the input; required and error text are available through native association and described-by.' },
    { title: 'Tokens', copy: 'Control padding, border roles, focus geometry and danger support come from the field contract.' },
    { title: 'Use it when', copy: 'A user supplies text, search terms or a precise value. Do not replace visible instruction with placeholder text.' },
  ],
  'search-fields': [
    { title: 'Anatomy', copy: 'Query field, clear action, scope, result count and the current result state form one recoverable loop.' },
    { title: 'States', copy: 'Query, searching, results, empty and error preserve the entered query and visible scope.' },
    { title: 'Accessibility', copy: 'Search has a named input, status announcement and a clear action that does not rely on an icon alone.' },
    { title: 'Tokens', copy: 'Search inherits Text Field geometry and adds result surfaces, local status and recovery emphasis.' },
    { title: 'Use it when', copy: 'The vocabulary is large enough to need retrieval. For a short fixed set, prefer select or segmented choice.' },
  ],
  'select-combobox': [
    { title: 'Anatomy', copy: 'Select owns a bounded value list; Combobox adds search; Action Menu invokes a command without selecting a value.' },
    { title: 'States', copy: 'Closed, open, highlighted, selected, disabled and no-match states depend on the chosen semantic primitive.' },
    { title: 'Accessibility', copy: 'Native select is the baseline. Composite behavior must expose name, expanded state, active option and keyboard path.' },
    { title: 'Tokens', copy: 'Shared control geometry does not erase the different overlay, option and command surfaces.' },
    { title: 'Use it when', copy: 'Choose the least complex control that matches the vocabulary and action, not the most visually flexible one.' },
  ],
  checkbox: [
    { title: 'Anatomy', copy: 'A native checkbox, label and optional group context represent one independent boolean choice.' },
    { title: 'States', copy: 'Unchecked, checked, indeterminate, focus, hover and disabled are all visible in the gallery.' },
    { title: 'Accessibility', copy: 'Native input semantics preserve checked and indeterminate meaning; the label remains clickable.' },
    { title: 'Tokens', copy: 'Accent, focus and disabled roles support the native shape without hiding the state in color.' },
    { title: 'Use it when', copy: 'Several choices can be selected independently. Use radio for one choice within a named group.' },
  ],
  radio: [
    { title: 'Anatomy', copy: 'Fieldset, legend and same-name radio inputs define one mutually exclusive decision.' },
    { title: 'States', copy: 'Unselected, selected, focus and disabled options show the current decision without ambiguous decoration.' },
    { title: 'Accessibility', copy: 'The legend names the group and native radio semantics expose the selected value and keyboard behavior.' },
    { title: 'Tokens', copy: 'Circle cue, focus ring and disabled contrast follow the control foundation.' },
    { title: 'Use it when', copy: 'Exactly one value must be chosen from a short visible list.' },
  ],
  toggle: [
    { title: 'Anatomy', copy: 'Label, switch track, thumb and immediate status describe one setting that changes now.' },
    { title: 'States', copy: 'On, off, focus, hover and disabled show availability without pretending there is a submit step.' },
    { title: 'Accessibility', copy: 'Switch role, checked state and label are exposed; a disabled toggle stays unavailable to keyboard input.' },
    { title: 'Tokens', copy: 'Track, thumb, interactive radius and semantic status roles preserve the control geometry.' },
    { title: 'Use it when', copy: 'The setting takes effect immediately. Use a checkbox when the value belongs to a later form submission.' },
  ],
  'segmented-control': [
    { title: 'Anatomy', copy: 'A short labelled group of adjacent buttons keeps related local choices visible at once.' },
    { title: 'States', copy: 'Selected, unselected, hover, focus, pressed, disabled option and compact size preserve the group shape.' },
    { title: 'Accessibility', copy: 'Buttons expose pressed state and the group has a label; activation updates the model on the next rendered frame.' },
    { title: 'Tokens', copy: 'Selected surface, control radius, gap and focus geometry are shared with the locale switcher.' },
    { title: 'Use it when', copy: 'The options are few, related and local. It is not primary navigation or a long filter list.' },
  ],
  'status-badges': [
    { title: 'Anatomy', copy: 'Tone, emphasis, icon cue and text label compose a status; the domain status is not the visual tone.' },
    { title: 'States', copy: 'Neutral, info, success, warning and danger can use subtle, standard or strong emphasis.' },
    { title: 'Accessibility', copy: 'The label and icon cue accompany hue so the status is recoverable without color perception.' },
    { title: 'Tokens', copy: 'Semantic foreground, surface, border and dot roles keep intensity consistent across contexts.' },
    { title: 'Use it when', copy: 'A compact state needs to travel with an object, row or action. Do not use it as ornamental decoration.' },
  ],
  'alerts-feedback': [
    { title: 'Anatomy', copy: 'Message, semantic cue, consequence and next action explain what happened and what can happen next.' },
    { title: 'States', copy: 'Info, success, warning, error and dismissible recovery vary by consequence, not by color preference.' },
    { title: 'Accessibility', copy: 'Use alert or status semantics only for the appropriate urgency and keep recovery keyboard reachable.' },
    { title: 'Tokens', copy: 'Support surface, border, icon and text roles are intensity-aware and contrast-tested.' },
    { title: 'Use it when', copy: 'The user needs feedback beyond a button label. Keep transient confirmation adjacent to the cause.' },
  ],
  menus: [
    { title: 'Anatomy', copy: 'Trigger, menu surface, command rows, separators, shortcuts and destructive grouping establish context.' },
    { title: 'States', copy: 'Closed, open, highlighted, disabled, destructive, long-list and outside-dismissal behavior are distinct.' },
    { title: 'Accessibility', copy: 'The keyboard path covers Enter, arrows, Escape, focus return and disabled commands without pointer dependence.' },
    { title: 'Tokens', copy: 'Overlay surface, menu shadow, focus geometry and command spacing preserve the frozen visual language.' },
    { title: 'Use it when', copy: 'A context has commands. Do not use it as a disguised select, segmented value group or primary navigation.' },
  ],
  tooltips: [
    { title: 'Anatomy', copy: 'A visible trigger owns a supplemental explanation that appears on hover or focus.' },
    { title: 'States', copy: 'Hidden, visible, delayed and Escape-dismissed states preserve the trigger geometry.' },
    { title: 'Accessibility', copy: 'The trigger receives described-by only while the tooltip is relevant; focus and keyboard dismissal remain safe.' },
    { title: 'Tokens', copy: 'Support surface, text, placement gap and focus ring are separate from Action Menu semantics.' },
    { title: 'Use it when', copy: 'The user may benefit from context but the essential instruction is already visible.' },
  ],
  'dialogs-overlays': [
    { title: 'Anatomy', copy: 'Trigger, scrim, labelled dialog surface, decision content and explicit close or action controls form the boundary.' },
    { title: 'States', copy: 'Closed, opening, open, validation failure and completed decision need different user feedback.' },
    { title: 'Accessibility', copy: 'Dialog naming, focus containment and restoration require a real overlay contract and human review.' },
    { title: 'Tokens', copy: 'Panel radius, surface overlay, elevation and focus geometry signal a focused decision.' },
    { title: 'Use it when', copy: 'A decision needs attention without replacing the surrounding context. Do not use it for ordinary reading.' },
  ],
  'cards-surfaces': [
    { title: 'Anatomy', copy: 'A card bounds an object; a panel groups work; a surface establishes a plane. Their responsibilities stay distinct.' },
    { title: 'States', copy: 'Default, selected, interactive, raised and inset treatments change hierarchy without universal rounding.' },
    { title: 'Accessibility', copy: 'Interactive cards need a real control and name; a visual surface alone is not an action.' },
    { title: 'Tokens', copy: 'Card and panel padding, radius, border and elevation aliases are reusable geometry decisions.' },
    { title: 'Use it when', copy: 'The boundary improves scanning or ownership. Remove the surface when it adds no task value.' },
  ],
  'lists-tables': [
    { title: 'Anatomy', copy: 'Header, identifier, primary content, status, row action, sort/filter scope and empty fallback preserve object identity.' },
    { title: 'States', copy: 'Loading, empty, selected, filtered, sorted, blocked and local overflow remain inspectable.' },
    { title: 'Accessibility', copy: 'Semantic table headers, visible scope and native controls keep dense data navigable.' },
    { title: 'Tokens', copy: 'Table header, row borders, density spacing and status roles are separate from page layout.' },
    { title: 'Use it when', copy: 'Relationships across records matter. Use a list when each item is read as an independent object.' },
  ],
  'progress-indicators': [
    { title: 'Anatomy', copy: 'Track or ring, value or activity label, surrounding task context and terminal result answer the progress question.' },
    { title: 'States', copy: 'Determinate, indeterminate, inline, step, paused, complete, error and skeleton are not interchangeable.' },
    { title: 'Accessibility', copy: 'Native progress or progressbar name/value plus text equivalents keep motion and color optional.' },
    { title: 'Tokens', copy: 'Track, accent, status and reduced-motion aliases communicate work without decorative animation.' },
    { title: 'Use it when', copy: 'The user benefits from knowing amount or activity. Skeleton belongs only to stable content geometry.' },
  ],
  'workflow-steps': [
    { title: 'Anatomy', copy: 'Ordered phases, current state, completed state and available navigation describe a multi-step task.' },
    { title: 'States', copy: 'Future, current, visited and terminal semantic tones remain independent dimensions.' },
    { title: 'Accessibility', copy: 'The list names the current step and the controls expose the same path without relying on spatial movement.' },
    { title: 'Tokens', copy: 'Step marker, connector, current surface and status cue use focused workflow geometry.' },
    { title: 'Use it when', copy: 'The order and progress through phases matter. It is not a quantity control or a generic process filler.' },
  ],
  'numeric-stepper': [
    { title: 'Anatomy', copy: 'Label, visible quantity, decrement and increment actions, bounds and unit make the exact value explicit.' },
    { title: 'States', copy: 'Minimum, middle, maximum, disabled and focus behavior show the clamp contract.' },
    { title: 'Accessibility', copy: 'Each action has a name tied to the quantity and the resulting value is visible.' },
    { title: 'Tokens', copy: 'Control padding, compact action geometry and focus ring keep the stepper dense but reachable.' },
    { title: 'Use it when', copy: 'The user changes a bounded integer by meaningful increments, such as package quantity.' },
  ],
  slider: [
    { title: 'Anatomy', copy: 'Range track, thumb, visible numeric value, unit and bounds express a continuous quantitative choice.' },
    { title: 'States', copy: 'Minimum, middle, maximum, focus and disabled are verified with a real native range input.' },
    { title: 'Accessibility', copy: 'The label and output expose min, max, step and current value without requiring visual track reading.' },
    { title: 'Tokens', copy: 'Track, thumb, accent and focus geometry are distinct from the Numeric Stepper surface.' },
    { title: 'Use it when', copy: 'An approximate range is useful and exact entry is not the primary task.' },
  ],
  'navigation-sidebars': [
    { title: 'Anatomy', copy: 'Brand, workspace context, grouped links, active row, search, disclosure and mobile drawer preserve location.' },
    { title: 'States', copy: 'Rest, active, hover, focus, collapsed group, mobile open and restored focus are visible.' },
    { title: 'Accessibility', copy: 'Router links, current location, disclosure controls, labelled navigation and Escape restoration are explicit.' },
    { title: 'Tokens', copy: 'Rail width, active radius, leading cue, spacing rhythm and quiet icon color are frozen decisions.' },
    { title: 'Use it when', copy: 'A product has stable information hierarchy. Keep the sidebar geometry; change content through owned navigation metadata.' },
  ],
};
