import type { DocumentationPageContent } from '../models/documentation-page';

export const COMPONENTS_CONTENT: readonly DocumentationPageContent[] = [
  {
    id: 'buttons', label: 'Buttons', icon: 'pi-external-link', group: 'COMPONENTS', kind: 'component', eyebrow: 'C1 / BUTTONS', title: 'Buttons make one next action obvious', intro: 'State gallery and live playground cover rest, hover, focus, pressed, disabled, processing, success and error.', summary: 'Processing preserves geometry and prevents duplicate activation.', keywords: ['button', 'loading', 'success', 'error', 'focus'], decision: 'Success can be adjacent feedback or brief local confirmation; not every button turns green.', foundation: 'Primary, secondary, quiet and danger intents use semantic action tokens.', angularContract: 'Native button or guarded link with explicit type, aria-busy, accessible name and disabled behavior.', adoptionMapping: 'Intent, size, icon, loading, state, full-width and navigation properties.'
  },
  {
    id: 'text-fields', label: 'Text Fields', icon: 'pi-pencil', group: 'COMPONENTS', kind: 'component', eyebrow: 'C2 / TEXT FIELDS', title: 'Text Fields expose input and recovery', intro: 'The approved field geometry is now a reusable first-class component with live and forced state evidence.', summary: 'Labels, help, error and value remain connected.', keywords: ['text field', 'input', 'label', 'error', 'readonly'], decision: 'Default and focus visual direction remains frozen.', foundation: 'Surface card, interactive border, focus ring and semantic danger roles.', angularContract: 'NexaTextField uses model signal, native input semantics and aria-describedby.', adoptionMapping: 'State, value, leading, trailing, helper, error and required properties.', status: 'FROZEN'
  },
  {
    id: 'search-fields', label: 'Search Fields', icon: 'pi-search', group: 'COMPONENTS', kind: 'component', eyebrow: 'C3 / SEARCH', title: 'Search makes query, progress and recovery visible', intro: 'Typing, searching, results, empty results, error and retry are interactive states, not labels in a table.', summary: 'Search geometry follows the field contract; result state stays nearby.', keywords: ['search', 'query', 'results', 'empty', 'retry'], decision: 'Search remains a field variant with truthful asynchronous phases.', foundation: 'Field geometry plus status text and result surface.', angularContract: 'Native search input, live status and explicit clear action.', adoptionMapping: 'Query, loading, results, empty and error states.'
  },
  {
    id: 'select-combobox', label: 'Select & Combobox', icon: 'pi-chevron-down', group: 'COMPONENTS', kind: 'component', eyebrow: 'C4 / CHOICE', title: 'Select, Combobox and Action Menu have different jobs', intro: 'A visual comparison prevents bounded choices, searchable vocabularies and commands from collapsing into one control.', summary: 'Native select is baseline; composite behavior earns its complexity.', keywords: ['select', 'combobox', 'action menu', 'choice'], decision: 'Use native semantics first.', foundation: 'Control geometry, surface card and focused border.', angularContract: 'Native select for bounded vocabulary; Angular Aria/CDK only for composite needs.', adoptionMapping: 'Control role, option density, open state and keyboard model.'
  },
  {
    id: 'checkbox', label: 'Checkbox', icon: 'pi-check-square', group: 'COMPONENTS', kind: 'component', eyebrow: 'C5 / CHECKBOX', title: 'Checkbox supports independent choices', intro: 'Real native checkboxes show unchecked, checked, indeterminate, hover, focus and disabled states.', summary: 'State is conveyed by native semantics, shape, icon and label.', keywords: ['checkbox', 'indeterminate', 'selection', 'keyboard'], decision: 'No div-based fake checkbox.', foundation: 'Accent blue, explicit label and 44px interaction target.', angularContract: 'Native input with indeterminate property set by the specimen.', adoptionMapping: 'Checked, indeterminate, disabled and focus properties.'
  },
  {
    id: 'radio', label: 'Radio', icon: 'pi-circle', group: 'COMPONENTS', kind: 'component', eyebrow: 'C6 / RADIO', title: 'Radio makes one choice within a named group', intro: 'The live group exposes unselected, selected, hover, focus and disabled states with fieldset semantics.', summary: 'Group name and current selection remain available to assistive technology.', keywords: ['radio', 'group', 'choice', 'keyboard'], decision: 'Native radio group owns selection semantics.', foundation: 'Circle cue plus text label; no color-only selection.', angularContract: 'Fieldset, legend, same-name inputs and checked binding.', adoptionMapping: 'Group label, option, selected, disabled and focus.'
  },
  {
    id: 'toggle', label: 'Toggle / Switch', icon: 'pi-power-off', group: 'COMPONENTS', kind: 'component', eyebrow: 'C7 / TOGGLE', title: 'Toggle communicates an immediate change', intro: 'Click and keyboard interaction update a real switch with on, off, focus and disabled evidence.', summary: 'Use for immediate settings, not deferred form choices.', keywords: ['toggle', 'switch', 'checked', 'keyboard'], decision: 'Immediate behavior is mandatory for toggle.', foundation: 'Track, thumb, label and state text use semantic tokens.', angularContract: 'NexaToggle wraps native checkbox semantics with role switch.', adoptionMapping: 'On/off, enabled/disabled, size and label.'
  },
  {
    id: 'segmented-control', label: 'Segmented Control', icon: 'pi-table', group: 'COMPONENTS', kind: 'component', eyebrow: 'C8 / SEGMENTED', title: 'Segmented Control keeps small related choices visible', intro: 'A real selection group demonstrates default, selected, hover, focus, disabled segment and compact size.', summary: 'Not main navigation.', keywords: ['segmented', 'filter', 'view mode', 'selection'], decision: 'Use only for a small set of closely related local choices.', foundation: 'Selected surface and blue cue align with sidebar language.', angularContract: 'Buttons expose aria-pressed and model updates.', adoptionMapping: 'Options, selected value, size, disabled option and state.'
  },
  {
    id: 'status-badges', label: 'Status & Badges', icon: 'pi-tag', group: 'COMPONENTS', kind: 'component', eyebrow: 'C9 / STATUS', title: 'Status is a composition, not text color', intro: 'Workflow, availability, priority and temperature vocabularies use icon, shape, label and semantic color.', summary: 'Hue supports meaning; it never carries meaning alone.', keywords: ['status', 'badge', 'workflow', 'temperature', 'priority'], decision: 'Status families stay semantically separate.', foundation: 'Surface, border, foreground and icon roles per semantic family.', angularContract: 'NexaStatusChip exposes tone and accessible text content.', adoptionMapping: 'Family, tone, icon cue, label and density.'
  },
  {
    id: 'alerts-feedback', label: 'Alerts & Feedback', icon: 'pi-bell', group: 'COMPONENTS', kind: 'component', eyebrow: 'C10 / FEEDBACK', title: 'Feedback tells what happened and what can happen next', intro: 'Success, warning, error, info and recovery examples use context-specific intensity.', summary: 'Recoverable errors make retry or correction visible.', keywords: ['alert', 'feedback', 'success', 'warning', 'error'], decision: 'Do not use green everywhere or generic error copy.', foundation: 'Semantic surface, border, icon, foreground and recovery action.', angularContract: 'Native region/alert semantics plus live status when appropriate.', adoptionMapping: 'Tone, urgency, persistence, action and dismissal.'
  },
  {
    id: 'menus', label: 'Menus & Action Menus', icon: 'pi-list', group: 'COMPONENTS', kind: 'component', eyebrow: 'C11 / MENUS', title: 'Menus expose commands in context', intro: 'Open, command selection, destructive separation, Escape and focus evidence are interactive.', summary: 'Action Menu invokes; it does not replace select or segmented choice.', keywords: ['menu', 'action', 'escape', 'keyboard'], decision: 'Commands remain distinct from value selection.', foundation: 'Raised surface, overlay shadow and clear focus cue.', angularContract: 'Native buttons plus menu role; CDK/Aria preferred for production composites.', adoptionMapping: 'Trigger, command, destructive group, open and keyboard states.'
  },
  {
    id: 'tooltips', label: 'Tooltips', icon: 'pi-question-circle', group: 'COMPONENTS', kind: 'component', eyebrow: 'C12 / TOOLTIPS', title: 'Tooltips supplement visible instruction', intro: 'Hover and focus show contextual help without hiding essential task guidance.', summary: 'Tooltips never carry critical meaning alone.', keywords: ['tooltip', 'help', 'hover', 'focus'], decision: 'Visible labels and instructions remain primary.', foundation: 'Dark neutral support surface with readable text.', angularContract: 'aria-describedby and focus-safe trigger.', adoptionMapping: 'Trigger, placement, delay, content and dismissal.'
  },
  {
    id: 'dialogs-overlays', label: 'Dialogs & Overlays', icon: 'pi-window-maximize', group: 'COMPONENTS', kind: 'component', eyebrow: 'C13 / OVERLAYS', title: 'Overlays focus a decision without losing context', intro: 'The live dialog demonstrates open, close, Escape, focus cue, scrim and recovery actions.', summary: 'Use for focused decisions, not ordinary content.', keywords: ['dialog', 'overlay', 'scrim', 'escape'], decision: 'Overlay elevation is meaningful and restrained.', foundation: 'Raised card, scrim and dialog radius tokens.', angularContract: 'Dialog role, labelled title, modal semantics and close action.', adoptionMapping: 'Size, scrim, entry, title, actions and dismissal.'
  },
  {
    id: 'cards-surfaces', label: 'Cards & Surfaces', icon: 'pi-stop', group: 'COMPONENTS', kind: 'component', eyebrow: 'C14 / SURFACES', title: 'Card and Panel responsibilities stay separate', intro: 'Object cards, grouped panels and visual planes use consistent border, padding, radius and state.', summary: 'No universal Box abstraction.', keywords: ['card', 'panel', 'surface', 'selected'], decision: 'A Card bounds an object; a Panel groups work; Surface defines a plane.', foundation: 'White surfaces, quiet borders and deliberate padding.', angularContract: 'NexaSurface stays small; docs composition primitives remain local.', adoptionMapping: 'Role, interaction, selection, padding and elevation.'
  },
  {
    id: 'lists-tables', label: 'Lists & Tables', icon: 'pi-table', group: 'COMPONENTS', kind: 'component', eyebrow: 'C15 / DATA', title: 'Data display preserves object identity and recovery', intro: 'Search, filter, sort, status, row action, empty and horizontal overflow are visible in one live table.', summary: 'Local horizontal scroll is allowed when table semantics require it.', keywords: ['table', 'list', 'sort', 'filter', 'overflow'], decision: 'Operational data needs explicit density and status cues.', foundation: 'Table header, row border, monospace identifiers and status composition.', angularContract: 'Semantic table, scoped headers, native controls and live result message.', adoptionMapping: 'Density, row state, sort, filter and empty behavior.'
  },
  {
    id: 'progress-indicators', label: 'Progress Indicators', icon: 'pi-spinner', group: 'COMPONENTS', kind: 'component', eyebrow: 'C16 / PROGRESS', title: 'Progress distinguishes known work from unknown duration', intro: 'Determinate progress, indeterminate activity, skeleton and reduced-motion behavior are shown side-by-side.', summary: 'Loading strategy follows knowledge of content geometry and duration.', keywords: ['progress', 'spinner', 'skeleton', 'determinate'], decision: 'Do not treat all loading as skeleton.', foundation: 'Progress accent, neutral track and text equivalent.', angularContract: 'Native progress where possible; status text and aria-valuenow when custom.', adoptionMapping: 'Type, value, label, motion and reduced-motion fallback.'
  },
  {
    id: 'workflow-steps', label: 'Workflow Steps', icon: 'pi-sitemap', group: 'COMPONENTS', kind: 'component', eyebrow: 'C17 / WORKFLOW', title: 'Workflow Steps describe a multi-phase task', intro: 'Client, Products, Delivery and Review are distinct from numeric quantity controls.', summary: 'Current, complete and upcoming phases remain legible.', keywords: ['workflow steps', 'phases', 'current step', 'review'], decision: 'Workflow Steps are not Numeric Steppers.', foundation: 'Step line, number/icon cue, current surface and completion status.', angularContract: 'Typed step model, current index and accessible list semantics.', adoptionMapping: 'Phase, current, completed, upcoming and navigation actions.'
  },
  {
    id: 'numeric-stepper', label: 'Numeric Stepper', icon: 'pi-sliders-h', group: 'COMPONENTS', kind: 'component', eyebrow: 'C18 / NUMERIC', title: 'Numeric Stepper changes an exact quantity', intro: 'Quantity, min boundary, max boundary, increment, decrement and disabled states are real.', summary: 'Display the affected value; do not hide numeric meaning in a track.', keywords: ['numeric stepper', 'quantity', 'min', 'max'], decision: 'Use for bounded increments, not broad ranges requiring many clicks.', foundation: 'Field surface, value emphasis and circular/clear actions.', angularContract: 'NexaNumericStepper clamps value and exposes labelled buttons.', adoptionMapping: 'Value, min, max, step, disabled and label.'
  },
  {
    id: 'slider', label: 'Slider', icon: 'pi-sliders-h', group: 'COMPONENTS', kind: 'component', eyebrow: 'C19 / SLIDER', title: 'Slider represents a meaningful quantitative range', intro: 'Temperature threshold, tolerance and dashboard range examples show minimum, middle, maximum, focus and disabled.', summary: 'Current value is always visible beside the track.', keywords: ['slider', 'range', 'temperature', 'threshold'], decision: 'Pair with field or numeric stepper when exact values matter.', foundation: 'Track, thumb, focus and semantic value roles.', angularContract: 'Native range input with labelled output.', adoptionMapping: 'Min, max, step, value, unit, focus and disabled.'
  },
  {
    id: 'navigation-sidebars', label: 'Navigation & Sidebars', icon: 'pi-bars', group: 'COMPONENTS', kind: 'component', eyebrow: 'C20 / NAVIGATION', title: 'Navigation preserves location and hierarchy', intro: 'The frozen Design Lab sidebar remains visible with grouped disclosure, active row, search and mobile drawer behavior.', summary: 'Current location uses label, icon, pale selected surface and blue leading cue.', keywords: ['navigation', 'sidebar', 'active', 'mobile', 'disclosure'], decision: 'Sidebar visual direction is frozen.', foundation: '284px desktop rail, 8px active radius, pale blue row and quiet PrimeIcons.', angularContract: 'RouterLinkActive, aria-current, disclosure buttons and focus restoration.', adoptionMapping: 'Group, item, active, badge, disclosure, search and drawer.', status: 'FROZEN'
  },
];
