import type { DocumentationAdoption } from '../models/documentation-page';

export const DOCUMENTATION_ADOPTION_BY_ID: Readonly<Record<string, DocumentationAdoption>> = {
  overview: 'LAB EVIDENCE ONLY', principles: 'LAB EVIDENCE ONLY', maturity: 'LAB EVIDENCE ONLY',
  color: 'LAB EVIDENCE ONLY', 'brand-logo': 'LAB EVIDENCE ONLY', typography: 'LAB EVIDENCE ONLY', 'layout-spacing': 'LAB EVIDENCE ONLY', 'shape-radius': 'LAB EVIDENCE ONLY', surfaces: 'LAB EVIDENCE ONLY', iconography: 'LAB EVIDENCE ONLY', motion: 'LAB EVIDENCE ONLY',
  buttons: 'PUBLIC COMPONENT', 'text-fields': 'PUBLIC COMPONENT', 'search-fields': 'COMPOSITION PATTERN', 'select-combobox': 'DOCUMENTED NATIVE PATTERN', checkbox: 'DOCUMENTED NATIVE PATTERN', radio: 'DOCUMENTED NATIVE PATTERN', toggle: 'PUBLIC COMPONENT', 'segmented-control': 'PUBLIC COMPONENT', 'status-badges': 'PUBLIC COMPONENT', 'alerts-feedback': 'DOCUMENTED NATIVE PATTERN', menus: 'PUBLIC COMPONENT', tooltips: 'PUBLIC COMPONENT', 'dialogs-overlays': 'DEFERRED / NOT PRODUCT READY', 'cards-surfaces': 'PUBLIC COMPONENT', 'lists-tables': 'DOCUMENTED NATIVE PATTERN', 'progress-indicators': 'DOCUMENTED NATIVE PATTERN', 'workflow-steps': 'DOCUMENTED NATIVE PATTERN', 'numeric-stepper': 'PUBLIC COMPONENT', slider: 'PUBLIC COMPONENT', 'navigation-sidebars': 'DEFERRED / NOT PRODUCT READY',
  forms: 'COMPOSITION PATTERN', 'search-filtering': 'COMPOSITION PATTERN', 'async-operations': 'COMPOSITION PATTERN', 'empty-loading-error': 'COMPOSITION PATTERN', authentication: 'COMPOSITION PATTERN', 'legal-content': 'COMPOSITION PATTERN', payments: 'COMPOSITION PATTERN', analytics: 'COMPOSITION PATTERN', 'dispatch-board': 'COMPOSITION PATTERN', 'data-dense-operations': 'COMPOSITION PATTERN', responsive: 'COMPOSITION PATTERN', catalog: 'COMPOSITION PATTERN', 'request-builder': 'COMPOSITION PATTERN', 'order-flow': 'COMPOSITION PATTERN', 'delivery-pod': 'COMPOSITION PATTERN', 'map-location': 'COMPOSITION PATTERN',
  'accessibility-lab': 'LAB EVIDENCE ONLY', 'contrast-lab': 'LAB EVIDENCE ONLY', heuristics: 'LAB EVIDENCE ONLY', 'input-modality': 'LAB EVIDENCE ONLY', 'component-maturity': 'LAB EVIDENCE ONLY',
  'angular-architecture': 'LAB EVIDENCE ONLY', 'design-tokens': 'LAB EVIDENCE ONLY', 'component-apis': 'LAB EVIDENCE ONLY', testing: 'LAB EVIDENCE ONLY', 'design-adoption': 'LAB EVIDENCE ONLY',
};
