import type { DocumentationPageContent } from '../models/documentation-page';

export const FOUNDATIONS_CONTENT: readonly DocumentationPageContent[] = [
  {
    id: 'color', label: 'Color', icon: 'pi-palette', group: 'FOUNDATIONS', kind: 'foundation', eyebrow: 'F1 / COLOR', title: 'Color communicates responsibility and state', intro: 'Blue anchors Nexa. Supporting families carry semantic work and remain measurable in the Contrast Lab.', summary: 'Every important color rule has a swatch, pairing and non-color cue.', keywords: ['color', 'blue', 'neutral', 'semantic', 'contrast'], decision: 'Light is canonical; increased contrast is an evaluation mode, not a second theme.', foundation: 'Primitive scales feed semantic roles, then component states.', angularContract: 'Token values are mechanically evaluated by the contrast utility and gate.', figmaMapping: 'Primitive variables, semantic aliases and contrast-mode values are named for later mapping.'
  },
  {
    id: 'brand-logo', label: 'Brand / Logo', icon: 'pi-image', group: 'FOUNDATIONS', kind: 'foundation', eyebrow: 'F2 / BRAND', title: 'The canonical Nexa mark stays intact at every size', intro: 'Supplied Nexa assets are rendered as the source of truth for branded specimens, inverse surfaces and compact use.', summary: 'Logo geometry is evidence, not a text approximation.', keywords: ['brand', 'logo', 'wordmark', 'inverse', 'safe space'], decision: 'Use the supplied canonical assets; do not redraw or fabricate variants.', foundation: 'Primary blue and inverse white assets are served from the versioned logo-nexa evidence folder.', angularContract: 'NexaLogo selects a real asset and exposes accessible alt/decorative behavior.', figmaMapping: 'Mark, variant, surface, minimum size and safe-space annotations.'
  },
  {
    id: 'typography', label: 'Typography', icon: 'pi-align-left', group: 'FOUNDATIONS', kind: 'foundation', eyebrow: 'F3 / TYPOGRAPHY', title: 'Type carries operational hierarchy', intro: 'Live specimens show primary, secondary and tertiary text at actual role sizes, weights and line heights.', summary: 'Plus Jakarta Sans, Inter and system mono remain the frozen candidate families.', keywords: ['typography', 'type scale', 'resize', 'contrast'], decision: 'Keep Plus Jakarta Sans, Inter and JetBrains/system mono; do not reopen family selection.', foundation: 'Display hierarchy uses Plus Jakarta Sans; dense UI uses Inter; identifiers use mono.', angularContract: 'Native headings, labels and text roles remain strict and resize-safe.', figmaMapping: 'Ten type roles map to text styles with family, size, weight, leading and usage.'
  },
  {
    id: 'layout-spacing', label: 'Layout & Spacing', icon: 'pi-arrows-alt', group: 'FOUNDATIONS', kind: 'foundation', eyebrow: 'F4 / LAYOUT', title: 'A 4px rhythm makes density deliberate', intro: 'Padding, gutters, alignment and responsive reflow are shown as measurable layout evidence.', summary: 'Use intrinsic grid and flex layout before shrinking content.', keywords: ['layout', 'spacing', 'padding', 'responsive', 'reflow'], decision: 'A small spacing scale protects alignment across documentation and specimens.', foundation: '4px primitives become 8, 12, 16, 24, 32 and 48px applications.', angularContract: 'CSS grid/flex with minmax; wide matrices scroll locally when semantics require it.', figmaMapping: 'Auto Layout contracts cover page stack, toolbar, panel, row and responsive gutter.'
  },
  {
    id: 'shape-radius', label: 'Shape & Radius', icon: 'pi-stop-circle', group: 'FOUNDATIONS', kind: 'foundation', eyebrow: 'F5 / SHAPE', title: 'Soft geometry without pill everything', intro: 'Radii are shown by responsibility: controls, cards, panels, overlays and compact status.', summary: 'Radius expresses hierarchy, not decoration.', keywords: ['shape', 'radius', 'card', 'control'], decision: 'Subtle rounded rectangles are canonical; full pills stay limited to compact status.', foundation: 'Semantic radii alias primitive values and remain consistent across states.', angularContract: 'Components own meaningful geometry; documentation wrappers do not leak APIs.', figmaMapping: 'Radius variables map to component properties and layout surfaces.'
  },
  {
    id: 'surfaces', label: 'Surfaces', icon: 'pi-stop', group: 'FOUNDATIONS', kind: 'foundation', eyebrow: 'F6 / SURFACES', title: 'Surfaces create a calm operational plane', intro: 'Canvas, primary, grouped, selected, raised and overlay planes are rendered with explicit responsibility.', summary: 'White structural surfaces sit on a cool canvas; elevation stays meaningful.', keywords: ['surfaces', 'canvas', 'card', 'panel', 'overlay'], decision: 'Surface, Card and Panel are distinct concepts; no universal Box abstraction.', foundation: 'Surface tokens define plane; component borders, padding and radius define object grouping.', angularContract: 'NexaSurface is small and composable; docs primitives remain docs-only.', figmaMapping: 'Surface roles map to fills, borders, radius and elevation variables.'
  },
  {
    id: 'iconography', label: 'Iconography', icon: 'pi-compass', group: 'FOUNDATIONS', kind: 'foundation', eyebrow: 'F7 / ICONOGRAPHY', title: 'Icons support labels and state', intro: 'PrimeIcons remain quiet, aligned and purposeful across navigation, actions and status evidence.', summary: 'Icon weight never competes with operational content.', keywords: ['icons', 'PrimeIcons', 'alignment', 'accessible name'], decision: 'Keep PrimeIcons as current candidate icon system.', foundation: '16–20px line icons, label relationships, state colors and non-color cues.', angularContract: 'Decorative icons are hidden; icon-only actions expose names and target geometry.', figmaMapping: 'Icon name, size, weight, label relationship and state color are explicit properties.'
  },
  {
    id: 'motion', label: 'Motion', icon: 'pi-bolt', group: 'FOUNDATIONS', kind: 'foundation', eyebrow: 'F8 / MOTION', title: 'Motion explains a state change', intro: 'Live specimens show cause, changed state, duration, easing and reduced-motion behavior.', summary: 'No continuous decorative animation.', keywords: ['motion', 'transition', 'reduced motion', 'easing'], decision: 'Short feedback motion is allowed when it preserves context and has a reason.', foundation: '140–250ms semantic durations with tokenized easing and reduced fallback.', angularContract: 'CSS transitions plus prefers-reduced-motion; no animation dependency.', figmaMapping: 'Motion entries expose trigger, property, duration, easing and fallback.'
  },
];

