import type { DocumentationPageContent } from '../models/documentation-page';

export const PATTERNS_CONTENT: readonly DocumentationPageContent[] = [
  {
    id: 'forms', label: 'Forms', icon: 'pi-file-edit', group: 'PATTERNS', kind: 'pattern', eyebrow: 'P1 / FORMS', title: 'Forms preserve context, validation and recovery', intro: 'Field groups, validation, disabled/read-only differences and submit feedback compose into one inspectable pattern.', summary: 'Inputs remain typed and recoverable.', keywords: ['forms', 'validation', 'readonly', 'submit'], decision: 'Use native semantics, visible labels and adjacent recovery.', foundation: 'Text field, select, checkbox, radio, button and feedback contracts.', angularContract: 'Signal-first local state with typed model boundaries.', figmaMapping: 'Form group, field state, action hierarchy and feedback.'
  },
  {
    id: 'search-filtering', label: 'Search & Filtering', icon: 'pi-filter', group: 'PATTERNS', kind: 'pattern', eyebrow: 'P2 / SEARCH', title: 'Search and filters show applied scope', intro: 'Query, filter selection, result count, empty state and clear recovery stay visible in a reusable composition.', summary: 'Search finds; filters narrow; applied state remains discoverable.', keywords: ['search', 'filter', 'query', 'empty'], decision: 'No hidden filter state.', foundation: 'Search field, segmented control, status and table contracts.', angularContract: 'Local signals for specimen; route/query state when deep links matter.', figmaMapping: 'Query, filter, applied, count, empty and retry.'
  },
  {
    id: 'async-operations', label: 'Async Operations', icon: 'pi-sync', group: 'PATTERNS', kind: 'pattern', eyebrow: 'P3 / ASYNC', title: 'Async work has visible phases', intro: 'Ready, pressed, processing, success, warning, error, retry and cancelled states can be stepped through.', summary: 'Every phase keeps context and an honest next action.', keywords: ['async', 'processing', 'retry', 'success', 'cancelled'], decision: 'Operation vocabulary is shared but component behavior remains specific.', foundation: 'Button, progress, alert, status and state sequence evidence.', angularContract: 'Typed phase model and signal-driven local transitions.', figmaMapping: 'Phase, label, progress, feedback and recovery.'
  },
  {
    id: 'empty-loading-error', label: 'Empty / Loading / Error', icon: 'pi-inbox', group: 'PATTERNS', kind: 'pattern', eyebrow: 'P4 / STATES', title: 'States answer what happened and what happens next', intro: 'Empty, loading, progress, success, warning, error, read-only and disabled examples are visual compositions.', summary: 'Recovery is part of the state, not an afterthought.', keywords: ['empty', 'loading', 'error', 'success', 'warning'], decision: 'Avoid generic error copy when context is known.', foundation: 'Icon, title, explanation, action and status severity.', angularContract: 'Native regions, live messages and deterministic specimen state.', figmaMapping: 'State, cue, copy, primary action and secondary recovery.'
  },
  {
    id: 'authentication', label: 'Authentication', icon: 'pi-lock', group: 'PATTERNS', kind: 'pattern', eyebrow: 'P5 / AUTHENTICATION', title: 'Authentication composes trusted brand and usable form evidence', intro: 'Brand surface, workspace selection, fields, validation, loading, success and localization are shown as a design-system pattern.', summary: 'Composition specimen, not production application screen.', keywords: ['authentication', 'workspace', 'login', 'localization'], decision: 'Use auth direction as a composition of frozen components.', foundation: 'Brand atmosphere remains a restrained exception; form surface stays canonical.', angularContract: 'Typed form state, accessible names and recoverable validation.', figmaMapping: 'Brand plane, workspace card, fields, action, locale and feedback.'
  },
  {
    id: 'legal-content', label: 'Legal Content', icon: 'pi-file', group: 'PATTERNS', kind: 'pattern', eyebrow: 'P6 / LEGAL', title: 'Legal content is readable without pretending to be policy', intro: 'Anchors, metadata, related documents and print-friendly reading are demonstrated with explicitly synthetic placeholder text.', summary: 'Formal legal approval remains outside the Design Lab.', keywords: ['legal', 'terms', 'privacy', 'security', 'anchors'], decision: 'Prepare structure only; do not author Nexa legal policy.', foundation: 'Readable measure, document hierarchy and local navigation.', angularContract: 'Semantic article, navigation, headings, anchors and print media rules.', figmaMapping: 'Document label, metadata, table of contents and long-form states.'
  },
  {
    id: 'payments', label: 'Payments', icon: 'pi-credit-card', group: 'PATTERNS', kind: 'pattern', eyebrow: 'P7 / PAYMENTS', title: 'Payment patterns separate safe presentation from provider diagnostics', intro: 'Synthetic payment method, empty/loading/unavailable states and user-safe failure are composed without a functional Stripe integration.', summary: 'Candidate pattern evidence, not financial behavior.', keywords: ['payments', 'method', 'placeholder', 'diagnostic', 'failure'], decision: 'Show states and boundaries; defer provider and domain contracts.', foundation: 'Quiet card surface, masked synthetic identity and semantic status.', angularContract: 'Typed local state with no payment SDK or backend dependency.', figmaMapping: 'Credit summary, method, placeholder, activity and failure states.'
  },
  {
    id: 'analytics', label: 'Analytics', icon: 'pi-chart-bar', group: 'PATTERNS', kind: 'pattern', eyebrow: 'P8 / ANALYTICS', title: 'Analytics visualizations answer a question before adding a chart', intro: 'Metric, distribution, text summary, data table fallback and no-data behavior define a reusable visual grammar.', summary: 'Evidence grammar, not a finished operational analytics screen.', keywords: ['analytics', 'metric', 'trend', 'table', 'no data'], decision: 'Every visualization needs a question, summary and accessible alternative.', foundation: 'Labels, values, non-color cues and lightweight geometry.', angularContract: 'CSS/SVG-ready specimens with semantic table fallback; no chart dependency.', figmaMapping: 'Question, visual, summary, legend and data alternative.'
  },
  {
    id: 'dispatch-board', label: 'Dispatch Board', icon: 'pi-truck', group: 'PATTERNS', kind: 'pattern', eyebrow: 'P9 / DISPATCH', title: 'Dispatch boards keep operational cards actionable and accessible', intro: 'Candidate columns and card states show a forward-looking composition without recreating FLOW or defining real transitions.', summary: 'Product / Domain decision required for permissions and movement.', keywords: ['dispatch', 'board', 'card', 'movement', 'keyboard'], decision: 'Design evidence only; drag-and-drop is never the sole interaction path.', foundation: 'Light grouped columns, readable cards and semantic status emphasis.', angularContract: 'Native buttons plus Action Menu provide keyboard-equivalent commands.', figmaMapping: 'Column, card density, selection, status and next safe action.'
  },
  {
    id: 'data-dense-operations', label: 'Data-Dense Operations', icon: 'pi-table', group: 'PATTERNS', kind: 'pattern', eyebrow: 'P10 / DATA-DENSE', title: 'Operational density remains structured, readable and recoverable', intro: 'KPI strip, critical alert, local scope, search, table, progress and state variants are generic evidence, not a production Inventory route.', summary: 'Wide data may scroll locally; the page itself must not overflow.', keywords: ['data dense', 'operations', 'inventory', 'table', 'kpi'], decision: 'Use density to support work, not to imply an accepted Inventory contract.', foundation: 'Table semantics, restrained surfaces, status and explicit loading/error states.', angularContract: 'Intrinsic grid, native table, signals and no JavaScript layout calculation.', figmaMapping: 'Toolbar, KPI strip, alert, table density and recovery states.'
  },
  {
    id: 'responsive', label: 'Responsive Composition', icon: 'pi-mobile', group: 'PATTERNS', kind: 'pattern', eyebrow: 'P11 / RESPONSIVE', title: 'Responsive behavior preserves task hierarchy', intro: 'The same composition is evaluated at 1440, 1024, 768, 390 and 320 widths with no accidental page overflow.', summary: 'Wide data can scroll locally; reading and controls reflow.', keywords: ['responsive', 'mobile', 'reflow', '320px', '400%'], decision: 'Protect hierarchy and hit targets before decorative density.', foundation: 'Intrinsic layout, gutters and component min widths.', angularContract: 'CSS media queries and semantic DOM, not duplicated route implementations.', figmaMapping: 'Desktop, tablet, mobile frame and reflow notes.'
  },
];

