import type { DocumentationPageContent } from '../models/documentation-page';

export const PATTERNS_CONTENT: readonly DocumentationPageContent[] = [
  {
    id: 'forms', label: 'Forms', icon: 'pi-file-edit', group: 'PATTERNS', kind: 'pattern', eyebrow: 'P1 / FORMS', title: 'Forms preserve context, validation and recovery', intro: 'Field groups, validation, disabled/read-only differences and submit feedback compose into one inspectable pattern.', summary: 'Inputs remain typed and recoverable.', keywords: ['forms', 'validation', 'readonly', 'submit'], decision: 'Use native semantics, visible labels and adjacent recovery.', foundation: 'Text field, select, checkbox, radio, button and feedback contracts.', angularContract: 'Signal-first local state with typed model boundaries.', adoptionMapping: 'Form group, field state, action hierarchy and feedback.'
  },
  {
    id: 'search-filtering', label: 'Search & Filtering', icon: 'pi-filter', group: 'PATTERNS', kind: 'pattern', eyebrow: 'P2 / SEARCH', title: 'Search and filters show applied scope', intro: 'Query, filter selection, result count, empty state and clear recovery stay visible in a reusable composition.', summary: 'Search finds; filters narrow; applied state remains discoverable.', keywords: ['search', 'filter', 'query', 'empty'], decision: 'No hidden filter state.', foundation: 'Search field, segmented control, status and table contracts.', angularContract: 'Local signals for specimen; route/query state when deep links matter.', adoptionMapping: 'Query, filter, applied, count, empty and retry.'
  },
  {
    id: 'async-operations', label: 'Async Operations', icon: 'pi-sync', group: 'PATTERNS', kind: 'pattern', eyebrow: 'P3 / ASYNC', title: 'Async work has visible phases', intro: 'Ready, pressed, processing, success, warning, error, retry and cancelled states can be stepped through.', summary: 'Every phase keeps context and an honest next action.', keywords: ['async', 'processing', 'retry', 'success', 'cancelled'], decision: 'Operation vocabulary is shared but component behavior remains specific.', foundation: 'Button, progress, alert, status and state sequence evidence.', angularContract: 'Typed phase model and signal-driven local transitions.', adoptionMapping: 'Phase, label, progress, feedback and recovery.'
  },
  {
    id: 'empty-loading-error', label: 'Empty / Loading / Error', icon: 'pi-inbox', group: 'PATTERNS', kind: 'pattern', eyebrow: 'P4 / STATES', title: 'States answer what happened and what happens next', intro: 'Empty, loading, progress, success, warning, error, read-only and disabled examples are visual compositions.', summary: 'Recovery is part of the state, not an afterthought.', keywords: ['empty', 'loading', 'error', 'success', 'warning'], decision: 'Avoid generic error copy when context is known.', foundation: 'Icon, title, explanation, action and status severity.', angularContract: 'Native regions, live messages and deterministic specimen state.', adoptionMapping: 'State, cue, copy, primary action and secondary recovery.'
  },
  {
    id: 'authentication', label: 'Authentication', icon: 'pi-lock', group: 'PATTERNS', kind: 'pattern', eyebrow: 'P5 / AUTHENTICATION', title: 'Authentication composes trusted brand and usable form evidence', intro: 'Brand surface, workspace selection, fields, validation, loading, success and localization are shown as a design-system pattern.', summary: 'Composition specimen, not production application screen.', keywords: ['authentication', 'workspace', 'login', 'localization'], decision: 'Use auth direction as a composition of frozen components.', foundation: 'Brand atmosphere remains a restrained exception; form surface stays canonical.', angularContract: 'Typed form state, accessible names and recoverable validation.', adoptionMapping: 'Brand plane, workspace card, fields, action, locale and feedback.'
  },
  {
    id: 'legal-content', label: 'Legal Content', icon: 'pi-file', group: 'PATTERNS', kind: 'pattern', eyebrow: 'P6 / LEGAL', title: 'Legal content is readable without pretending to be policy', intro: 'Anchors, metadata, related documents and print-friendly reading are demonstrated with explicitly synthetic placeholder text.', summary: 'Formal legal approval remains outside the Design Lab.', keywords: ['legal', 'terms', 'privacy', 'security', 'anchors'], decision: 'Prepare structure only; do not author Nexa legal policy.', foundation: 'Readable measure, document hierarchy and local navigation.', angularContract: 'Semantic article, navigation, headings, anchors and print media rules.', adoptionMapping: 'Document label, metadata, table of contents and long-form states.'
  },
  {
    id: 'payments', label: 'Payments', icon: 'pi-credit-card', group: 'PATTERNS', kind: 'pattern', eyebrow: 'P7 / PAYMENTS', title: 'Payment patterns separate safe presentation from provider diagnostics', intro: 'Synthetic payment method, empty/loading/unavailable states and user-safe failure are composed without a functional Stripe integration.', summary: 'Candidate pattern evidence, not financial behavior.', keywords: ['payments', 'method', 'placeholder', 'diagnostic', 'failure'], decision: 'Show states and boundaries; defer provider and domain contracts.', foundation: 'Quiet card surface, masked synthetic identity and semantic status.', angularContract: 'Typed local state with no payment SDK or backend dependency.', adoptionMapping: 'Credit summary, method, placeholder, activity and failure states.'
  },
  {
    id: 'analytics', label: 'Analytics', icon: 'pi-chart-bar', group: 'PATTERNS', kind: 'pattern', eyebrow: 'P8 / ANALYTICS', title: 'Analytics visualizations answer a question before adding a chart', intro: 'Metric, distribution, text summary, data table fallback and no-data behavior define a reusable visual grammar.', summary: 'Evidence grammar, not a finished operational analytics screen.', keywords: ['analytics', 'metric', 'trend', 'table', 'no data'], decision: 'Every visualization needs a question, summary and accessible alternative.', foundation: 'Labels, values, non-color cues and lightweight geometry.', angularContract: 'CSS/SVG-ready specimens with semantic table fallback; no chart dependency.', adoptionMapping: 'Question, visual, summary, legend and data alternative.'
  },
  {
    id: 'dispatch-board', label: 'Dispatch Board', icon: 'pi-truck', group: 'PATTERNS', kind: 'pattern', eyebrow: 'P9 / DISPATCH', title: 'Dispatch boards keep operational cards actionable and accessible', intro: 'Candidate columns and card states show a forward-looking composition without recreating FLOW or defining real transitions.', summary: 'Product / Domain decision required for permissions and movement.', keywords: ['dispatch', 'board', 'card', 'movement', 'keyboard'], decision: 'Design evidence only; drag-and-drop is never the sole interaction path.', foundation: 'Light grouped columns, readable cards and semantic status emphasis.', angularContract: 'Native buttons plus Action Menu provide keyboard-equivalent commands.', adoptionMapping: 'Column, card density, selection, status and next safe action.'
  },
  {
    id: 'data-dense-operations', label: 'Data-Dense Operations', icon: 'pi-table', group: 'PATTERNS', kind: 'pattern', eyebrow: 'P10 / DATA-DENSE', title: 'Operational density remains structured, readable and recoverable', intro: 'KPI strip, critical alert, local scope, search, table, progress and state variants are generic evidence, not a production Inventory route.', summary: 'Wide data may scroll locally; the page itself must not overflow.', keywords: ['data dense', 'operations', 'inventory', 'table', 'kpi'], decision: 'Use density to support work, not to imply an accepted Inventory contract.', foundation: 'Table semantics, restrained surfaces, status and explicit loading/error states.', angularContract: 'Intrinsic grid, native table, signals and no JavaScript layout calculation.', adoptionMapping: 'Toolbar, KPI strip, alert, table density and recovery states.'
  },
  {
    id: 'responsive', label: 'Responsive Composition', icon: 'pi-mobile', group: 'PATTERNS', kind: 'pattern', eyebrow: 'P11 / RESPONSIVE', title: 'Responsive behavior preserves task hierarchy', intro: 'The same composition is evaluated at 1440, 1024, 768, 390 and 320 widths with no accidental page overflow.', summary: 'Wide data can scroll locally; reading and controls reflow.', keywords: ['responsive', 'mobile', 'reflow', '320px', '400%'], decision: 'Protect hierarchy and hit targets before decorative density.', foundation: 'Intrinsic layout, gutters and component min widths.', angularContract: 'CSS media queries and semantic DOM, not duplicated route implementations.', adoptionMapping: 'Desktop, tablet, mobile frame and reflow notes.'
  },
  {
    id: 'catalog', label: 'Catalog Browsing', icon: 'pi-box', group: 'PATTERNS', kind: 'pattern', eyebrow: 'P12 / CATALOG', title: 'Catalog browsing makes product identity and availability legible', intro: 'Product cards and detail evidence keep temperature, availability and the next safe action visible on white product surfaces.', summary: 'Browsing supports a request; it never reserves inventory.', keywords: ['catalog', 'product', 'card', 'detail', 'availability'], decision: 'Product identity precedes request intent.', foundation: 'Card, status, icon, typography and spacing contracts.', angularContract: 'Typed local product specimens with semantic selection.', adoptionMapping: 'Product card and detail ownership remain open for product review.'
  },
  {
    id: 'request-builder', label: 'Request Builder', icon: 'pi-shopping-cart', group: 'PATTERNS', kind: 'pattern', eyebrow: 'P13 / REQUEST', title: 'Cart, draft request and order remain separate objects', intro: 'Editable cart intent becomes a draft request only after the user reviews quantity, documents and delivery context.', summary: 'The cart is not an order and does not reserve inventory.', keywords: ['cart', 'draft', 'request', 'quantity', 'documents'], decision: 'Do not collapse buyer intent and sales outcome into one screen.', foundation: 'Numeric controls, status, form and action contracts.', angularContract: 'Local signals demonstrate editable state without backend claims.', adoptionMapping: 'Cart and request builder ownership require product confirmation.'
  },
  {
    id: 'order-flow', label: 'Order Flow', icon: 'pi-check-circle', group: 'PATTERNS', kind: 'pattern', eyebrow: 'P14 / ORDER', title: 'Order confirmation and status keep ownership visible', intro: 'Confirmation, business documents and status progression are shown as distinct evidence with explicit terminal meaning.', summary: 'Confirmation is not delivery proof.', keywords: ['order', 'confirmation', 'status', 'documents'], decision: 'Keep request, order and document ownership visible.', foundation: 'State sequence, status, document and action contracts.', angularContract: 'Docs-only deterministic phases; no backend transition is invented.', adoptionMapping: 'Order state composition awaits product-domain review.'
  },
  {
    id: 'delivery-pod', label: 'Delivery / Proof', icon: 'pi-truck', group: 'PATTERNS', kind: 'pattern', eyebrow: 'P15 / DELIVERY', title: 'Delivery evidence makes receipt and condition reviewable', intro: 'Proof-of-delivery presentation names destination, receiver, time and evidence attachment without defining a driver application.', summary: 'Execution is documented as runway evidence.', keywords: ['delivery', 'POD', 'receipt', 'cold-chain'], decision: 'Do not make mobile execution a V1 product claim.', foundation: 'Status, document, location and recovery contracts.', angularContract: 'Accessible local state; provider and domain integrations deferred.', adoptionMapping: 'Delivery handoff remains a cross-team product decision.'
  },
  {
    id: 'map-location', label: 'Map / Location', icon: 'pi-directions', group: 'PATTERNS', kind: 'pattern', eyebrow: 'P16 / LOCATION', title: 'Location evidence has an accessible non-map path', intro: 'Provider-agnostic location composition shows origin, destination, purpose and directions with a semantic list alternative.', summary: 'No map provider or driver contract is selected.', keywords: ['map', 'location', 'provider', 'directions', 'accessibility'], decision: 'The map enhances location context; it does not own the information.', foundation: 'Surfaces, iconography, status and responsive composition.', angularContract: 'Static CSS evidence with accessible controls and text fallback.', adoptionMapping: 'Provider and ownership are explicitly open.'
  },
];
